// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: dnssec.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DNSSECService_GetStatus_FullMethodName     = "/dnsscience.v1.DNSSECService/GetStatus"
	DNSSECService_Sign_FullMethodName          = "/dnsscience.v1.DNSSECService/Sign"
	DNSSECService_Rollover_FullMethodName      = "/dnsscience.v1.DNSSECService/Rollover"
	DNSSECService_GetDS_FullMethodName         = "/dnsscience.v1.DNSSECService/GetDS"
	DNSSECService_GenerateKey_FullMethodName   = "/dnsscience.v1.DNSSECService/GenerateKey"
	DNSSECService_ImportKey_FullMethodName     = "/dnsscience.v1.DNSSECService/ImportKey"
	DNSSECService_ExportKey_FullMethodName     = "/dnsscience.v1.DNSSECService/ExportKey"
	DNSSECService_DeleteKey_FullMethodName     = "/dnsscience.v1.DNSSECService/DeleteKey"
	DNSSECService_ValidateChain_FullMethodName = "/dnsscience.v1.DNSSECService/ValidateChain"
	DNSSECService_WatchKeys_FullMethodName     = "/dnsscience.v1.DNSSECService/WatchKeys"
)

// DNSSECServiceClient is the client API for DNSSECService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DNSSECService manages DNSSEC operations
type DNSSECServiceClient interface {
	// GetStatus returns DNSSEC status for a zone
	GetStatus(ctx context.Context, in *DNSSECStatusRequest, opts ...grpc.CallOption) (*DNSSECStatusResponse, error)
	// Sign re-signs a zone
	Sign(ctx context.Context, in *SignZoneRequest, opts ...grpc.CallOption) (*SignZoneResponse, error)
	// Rollover initiates key rollover
	Rollover(ctx context.Context, in *RolloverRequest, opts ...grpc.CallOption) (*RolloverResponse, error)
	// GetDS returns DS records for parent delegation
	GetDS(ctx context.Context, in *GetDSRequest, opts ...grpc.CallOption) (*GetDSResponse, error)
	// GenerateKey generates a new DNSSEC key
	GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error)
	// ImportKey imports an existing DNSSEC key
	ImportKey(ctx context.Context, in *ImportKeyRequest, opts ...grpc.CallOption) (*ImportKeyResponse, error)
	// ExportKey exports a DNSSEC key
	ExportKey(ctx context.Context, in *ExportKeyRequest, opts ...grpc.CallOption) (*ExportKeyResponse, error)
	// DeleteKey deletes a DNSSEC key
	DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error)
	// ValidateChain validates the DNSSEC chain
	ValidateChain(ctx context.Context, in *ValidateChainRequest, opts ...grpc.CallOption) (*ValidateChainResponse, error)
	// WatchKeys streams DNSSEC key events
	WatchKeys(ctx context.Context, in *WatchKeysRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSSECEvent], error)
}

type dNSSECServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDNSSECServiceClient(cc grpc.ClientConnInterface) DNSSECServiceClient {
	return &dNSSECServiceClient{cc}
}

func (c *dNSSECServiceClient) GetStatus(ctx context.Context, in *DNSSECStatusRequest, opts ...grpc.CallOption) (*DNSSECStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSSECStatusResponse)
	err := c.cc.Invoke(ctx, DNSSECService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSSECServiceClient) Sign(ctx context.Context, in *SignZoneRequest, opts ...grpc.CallOption) (*SignZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignZoneResponse)
	err := c.cc.Invoke(ctx, DNSSECService_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSSECServiceClient) Rollover(ctx context.Context, in *RolloverRequest, opts ...grpc.CallOption) (*RolloverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RolloverResponse)
	err := c.cc.Invoke(ctx, DNSSECService_Rollover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSSECServiceClient) GetDS(ctx context.Context, in *GetDSRequest, opts ...grpc.CallOption) (*GetDSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDSResponse)
	err := c.cc.Invoke(ctx, DNSSECService_GetDS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSSECServiceClient) GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateKeyResponse)
	err := c.cc.Invoke(ctx, DNSSECService_GenerateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSSECServiceClient) ImportKey(ctx context.Context, in *ImportKeyRequest, opts ...grpc.CallOption) (*ImportKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportKeyResponse)
	err := c.cc.Invoke(ctx, DNSSECService_ImportKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSSECServiceClient) ExportKey(ctx context.Context, in *ExportKeyRequest, opts ...grpc.CallOption) (*ExportKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportKeyResponse)
	err := c.cc.Invoke(ctx, DNSSECService_ExportKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSSECServiceClient) DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyResponse)
	err := c.cc.Invoke(ctx, DNSSECService_DeleteKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSSECServiceClient) ValidateChain(ctx context.Context, in *ValidateChainRequest, opts ...grpc.CallOption) (*ValidateChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateChainResponse)
	err := c.cc.Invoke(ctx, DNSSECService_ValidateChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dNSSECServiceClient) WatchKeys(ctx context.Context, in *WatchKeysRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DNSSECEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DNSSECService_ServiceDesc.Streams[0], DNSSECService_WatchKeys_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchKeysRequest, DNSSECEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DNSSECService_WatchKeysClient = grpc.ServerStreamingClient[DNSSECEvent]

// DNSSECServiceServer is the server API for DNSSECService service.
// All implementations must embed UnimplementedDNSSECServiceServer
// for forward compatibility.
//
// DNSSECService manages DNSSEC operations
type DNSSECServiceServer interface {
	// GetStatus returns DNSSEC status for a zone
	GetStatus(context.Context, *DNSSECStatusRequest) (*DNSSECStatusResponse, error)
	// Sign re-signs a zone
	Sign(context.Context, *SignZoneRequest) (*SignZoneResponse, error)
	// Rollover initiates key rollover
	Rollover(context.Context, *RolloverRequest) (*RolloverResponse, error)
	// GetDS returns DS records for parent delegation
	GetDS(context.Context, *GetDSRequest) (*GetDSResponse, error)
	// GenerateKey generates a new DNSSEC key
	GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error)
	// ImportKey imports an existing DNSSEC key
	ImportKey(context.Context, *ImportKeyRequest) (*ImportKeyResponse, error)
	// ExportKey exports a DNSSEC key
	ExportKey(context.Context, *ExportKeyRequest) (*ExportKeyResponse, error)
	// DeleteKey deletes a DNSSEC key
	DeleteKey(context.Context, *DeleteKeyRequest) (*DeleteKeyResponse, error)
	// ValidateChain validates the DNSSEC chain
	ValidateChain(context.Context, *ValidateChainRequest) (*ValidateChainResponse, error)
	// WatchKeys streams DNSSEC key events
	WatchKeys(*WatchKeysRequest, grpc.ServerStreamingServer[DNSSECEvent]) error
	mustEmbedUnimplementedDNSSECServiceServer()
}

// UnimplementedDNSSECServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDNSSECServiceServer struct{}

func (UnimplementedDNSSECServiceServer) GetStatus(context.Context, *DNSSECStatusRequest) (*DNSSECStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDNSSECServiceServer) Sign(context.Context, *SignZoneRequest) (*SignZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedDNSSECServiceServer) Rollover(context.Context, *RolloverRequest) (*RolloverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollover not implemented")
}
func (UnimplementedDNSSECServiceServer) GetDS(context.Context, *GetDSRequest) (*GetDSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDS not implemented")
}
func (UnimplementedDNSSECServiceServer) GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateKey not implemented")
}
func (UnimplementedDNSSECServiceServer) ImportKey(context.Context, *ImportKeyRequest) (*ImportKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportKey not implemented")
}
func (UnimplementedDNSSECServiceServer) ExportKey(context.Context, *ExportKeyRequest) (*ExportKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportKey not implemented")
}
func (UnimplementedDNSSECServiceServer) DeleteKey(context.Context, *DeleteKeyRequest) (*DeleteKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKey not implemented")
}
func (UnimplementedDNSSECServiceServer) ValidateChain(context.Context, *ValidateChainRequest) (*ValidateChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateChain not implemented")
}
func (UnimplementedDNSSECServiceServer) WatchKeys(*WatchKeysRequest, grpc.ServerStreamingServer[DNSSECEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchKeys not implemented")
}
func (UnimplementedDNSSECServiceServer) mustEmbedUnimplementedDNSSECServiceServer() {}
func (UnimplementedDNSSECServiceServer) testEmbeddedByValue()                       {}

// UnsafeDNSSECServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DNSSECServiceServer will
// result in compilation errors.
type UnsafeDNSSECServiceServer interface {
	mustEmbedUnimplementedDNSSECServiceServer()
}

func RegisterDNSSECServiceServer(s grpc.ServiceRegistrar, srv DNSSECServiceServer) {
	// If the following call panics, it indicates UnimplementedDNSSECServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DNSSECService_ServiceDesc, srv)
}

func _DNSSECService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DNSSECStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSSECServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSSECService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSSECServiceServer).GetStatus(ctx, req.(*DNSSECStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSSECService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSSECServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSSECService_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSSECServiceServer).Sign(ctx, req.(*SignZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSSECService_Rollover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RolloverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSSECServiceServer).Rollover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSSECService_Rollover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSSECServiceServer).Rollover(ctx, req.(*RolloverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSSECService_GetDS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSSECServiceServer).GetDS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSSECService_GetDS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSSECServiceServer).GetDS(ctx, req.(*GetDSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSSECService_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSSECServiceServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSSECService_GenerateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSSECServiceServer).GenerateKey(ctx, req.(*GenerateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSSECService_ImportKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSSECServiceServer).ImportKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSSECService_ImportKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSSECServiceServer).ImportKey(ctx, req.(*ImportKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSSECService_ExportKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSSECServiceServer).ExportKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSSECService_ExportKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSSECServiceServer).ExportKey(ctx, req.(*ExportKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSSECService_DeleteKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSSECServiceServer).DeleteKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSSECService_DeleteKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSSECServiceServer).DeleteKey(ctx, req.(*DeleteKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSSECService_ValidateChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DNSSECServiceServer).ValidateChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DNSSECService_ValidateChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DNSSECServiceServer).ValidateChain(ctx, req.(*ValidateChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DNSSECService_WatchKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchKeysRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DNSSECServiceServer).WatchKeys(m, &grpc.GenericServerStream[WatchKeysRequest, DNSSECEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DNSSECService_WatchKeysServer = grpc.ServerStreamingServer[DNSSECEvent]

// DNSSECService_ServiceDesc is the grpc.ServiceDesc for DNSSECService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DNSSECService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsscience.v1.DNSSECService",
	HandlerType: (*DNSSECServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _DNSSECService_GetStatus_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _DNSSECService_Sign_Handler,
		},
		{
			MethodName: "Rollover",
			Handler:    _DNSSECService_Rollover_Handler,
		},
		{
			MethodName: "GetDS",
			Handler:    _DNSSECService_GetDS_Handler,
		},
		{
			MethodName: "GenerateKey",
			Handler:    _DNSSECService_GenerateKey_Handler,
		},
		{
			MethodName: "ImportKey",
			Handler:    _DNSSECService_ImportKey_Handler,
		},
		{
			MethodName: "ExportKey",
			Handler:    _DNSSECService_ExportKey_Handler,
		},
		{
			MethodName: "DeleteKey",
			Handler:    _DNSSECService_DeleteKey_Handler,
		},
		{
			MethodName: "ValidateChain",
			Handler:    _DNSSECService_ValidateChain_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchKeys",
			Handler:       _DNSSECService_WatchKeys_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "dnssec.proto",
}
