package engine

import (
	"math"
	"strings"
)

// IsDGA checks if a domain looks like it was generated by a Domain Generation Algorithm (DGA).
// It uses entropy analysis and heuristic checks optimized for speed (< 500ns).
func IsDGA(domain string) bool {
	// Removes TLD (rough approximation, taking last part)
	parts := strings.Split(domain, ".")
	if len(parts) > 1 {
		// Checks the SLD (Second Level Domain)
		domain = parts[len(parts)-2]
	}

	// Short domains are rarely DGA
	if len(domain) < 6 {
		return false
	}

	// Calculate entropy
	entropy := calculateEntropy(domain)

	// Thresholds: High entropy is suspicious
	// 4.0 is typical cutoff for alphanumeric random strings > 8 chars
	if entropy > 4.2 {
		return true
	}

	return false
}

// calculateEntropy calculates Shannon entropy of the string
func calculateEntropy(s string) float64 {
	if len(s) == 0 {
		return 0
	}

	// Count character frequencies
	// Optimization: Use array instead of map for ASCII
	counts := make([]int, 256)
	for i := 0; i < len(s); i++ {
		counts[s[i]]++
	}

	entropy := 0.0
	length := float64(len(s))

	for _, count := range counts {
		if count > 0 {
			p := float64(count) / length
			entropy -= p * math.Log2(p)
		}
	}

	return entropy
}
