// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: cache.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CacheService_GetStats_FullMethodName   = "/dnsscience.v1.CacheService/GetStats"
	CacheService_Lookup_FullMethodName     = "/dnsscience.v1.CacheService/Lookup"
	CacheService_Flush_FullMethodName      = "/dnsscience.v1.CacheService/Flush"
	CacheService_Prefetch_FullMethodName   = "/dnsscience.v1.CacheService/Prefetch"
	CacheService_WatchCache_FullMethodName = "/dnsscience.v1.CacheService/WatchCache"
)

// CacheServiceClient is the client API for CacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CacheService manages DNS cache operations
type CacheServiceClient interface {
	// GetStats returns cache statistics
	GetStats(ctx context.Context, in *GetCacheStatsRequest, opts ...grpc.CallOption) (*GetCacheStatsResponse, error)
	// Lookup retrieves specific cache entries
	Lookup(ctx context.Context, in *CacheLookupRequest, opts ...grpc.CallOption) (*CacheLookupResponse, error)
	// Flush clears cache entries
	Flush(ctx context.Context, in *FlushCacheRequest, opts ...grpc.CallOption) (*FlushCacheResponse, error)
	// Prefetch adds entries to cache
	Prefetch(ctx context.Context, in *PrefetchRequest, opts ...grpc.CallOption) (*PrefetchResponse, error)
	// WatchCache streams cache events (hits, misses, evictions)
	WatchCache(ctx context.Context, in *WatchCacheRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CacheEvent], error)
}

type cacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheServiceClient(cc grpc.ClientConnInterface) CacheServiceClient {
	return &cacheServiceClient{cc}
}

func (c *cacheServiceClient) GetStats(ctx context.Context, in *GetCacheStatsRequest, opts ...grpc.CallOption) (*GetCacheStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCacheStatsResponse)
	err := c.cc.Invoke(ctx, CacheService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Lookup(ctx context.Context, in *CacheLookupRequest, opts ...grpc.CallOption) (*CacheLookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheLookupResponse)
	err := c.cc.Invoke(ctx, CacheService_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Flush(ctx context.Context, in *FlushCacheRequest, opts ...grpc.CallOption) (*FlushCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushCacheResponse)
	err := c.cc.Invoke(ctx, CacheService_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Prefetch(ctx context.Context, in *PrefetchRequest, opts ...grpc.CallOption) (*PrefetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrefetchResponse)
	err := c.cc.Invoke(ctx, CacheService_Prefetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) WatchCache(ctx context.Context, in *WatchCacheRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CacheEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CacheService_ServiceDesc.Streams[0], CacheService_WatchCache_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchCacheRequest, CacheEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CacheService_WatchCacheClient = grpc.ServerStreamingClient[CacheEvent]

// CacheServiceServer is the server API for CacheService service.
// All implementations must embed UnimplementedCacheServiceServer
// for forward compatibility.
//
// CacheService manages DNS cache operations
type CacheServiceServer interface {
	// GetStats returns cache statistics
	GetStats(context.Context, *GetCacheStatsRequest) (*GetCacheStatsResponse, error)
	// Lookup retrieves specific cache entries
	Lookup(context.Context, *CacheLookupRequest) (*CacheLookupResponse, error)
	// Flush clears cache entries
	Flush(context.Context, *FlushCacheRequest) (*FlushCacheResponse, error)
	// Prefetch adds entries to cache
	Prefetch(context.Context, *PrefetchRequest) (*PrefetchResponse, error)
	// WatchCache streams cache events (hits, misses, evictions)
	WatchCache(*WatchCacheRequest, grpc.ServerStreamingServer[CacheEvent]) error
	mustEmbedUnimplementedCacheServiceServer()
}

// UnimplementedCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCacheServiceServer struct{}

func (UnimplementedCacheServiceServer) GetStats(context.Context, *GetCacheStatsRequest) (*GetCacheStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedCacheServiceServer) Lookup(context.Context, *CacheLookupRequest) (*CacheLookupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedCacheServiceServer) Flush(context.Context, *FlushCacheRequest) (*FlushCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedCacheServiceServer) Prefetch(context.Context, *PrefetchRequest) (*PrefetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prefetch not implemented")
}
func (UnimplementedCacheServiceServer) WatchCache(*WatchCacheRequest, grpc.ServerStreamingServer[CacheEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchCache not implemented")
}
func (UnimplementedCacheServiceServer) mustEmbedUnimplementedCacheServiceServer() {}
func (UnimplementedCacheServiceServer) testEmbeddedByValue()                      {}

// UnsafeCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheServiceServer will
// result in compilation errors.
type UnsafeCacheServiceServer interface {
	mustEmbedUnimplementedCacheServiceServer()
}

func RegisterCacheServiceServer(s grpc.ServiceRegistrar, srv CacheServiceServer) {
	// If the following call panics, it indicates UnimplementedCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CacheService_ServiceDesc, srv)
}

func _CacheService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCacheStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).GetStats(ctx, req.(*GetCacheStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheLookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Lookup(ctx, req.(*CacheLookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Flush(ctx, req.(*FlushCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Prefetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrefetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Prefetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheService_Prefetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Prefetch(ctx, req.(*PrefetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_WatchCache_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchCacheRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CacheServiceServer).WatchCache(m, &grpc.GenericServerStream[WatchCacheRequest, CacheEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CacheService_WatchCacheServer = grpc.ServerStreamingServer[CacheEvent]

// CacheService_ServiceDesc is the grpc.ServiceDesc for CacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsscience.v1.CacheService",
	HandlerType: (*CacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _CacheService_GetStats_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _CacheService_Lookup_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _CacheService_Flush_Handler,
		},
		{
			MethodName: "Prefetch",
			Handler:    _CacheService_Prefetch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchCache",
			Handler:       _CacheService_WatchCache_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cache.proto",
}
