// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: dns.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryRequest represents a single DNS query
type QueryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                                                           // A, AAAA, MX, CNAME, SOA, TXT, etc.
	Class            string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`                                                                         // IN (default), CH, HS
	Dnssec           bool                   `protobuf:"varint,4,opt,name=dnssec,proto3" json:"dnssec,omitempty"`                                                                      // Request DNSSEC validation
	RecursionDesired bool                   `protobuf:"varint,5,opt,name=recursion_desired,json=recursionDesired,proto3" json:"recursion_desired,omitempty"`                          // RD flag
	CheckingDisabled bool                   `protobuf:"varint,6,opt,name=checking_disabled,json=checkingDisabled,proto3" json:"checking_disabled,omitempty"`                          // CD flag (skip DNSSEC validation)
	ServerId         string                 `protobuf:"bytes,7,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`                                                   // Target specific server (optional)
	Tags             map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom tags for request
	TraceId          string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                                      // Correlation/trace ID for logging
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueryRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *QueryRequest) GetDnssec() bool {
	if x != nil {
		return x.Dnssec
	}
	return false
}

func (x *QueryRequest) GetRecursionDesired() bool {
	if x != nil {
		return x.RecursionDesired
	}
	return false
}

func (x *QueryRequest) GetCheckingDisabled() bool {
	if x != nil {
		return x.CheckingDisabled
	}
	return false
}

func (x *QueryRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *QueryRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *QueryRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// QueryResponse represents a DNS response
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response code
	Rcode     int32  `protobuf:"varint,1,opt,name=rcode,proto3" json:"rcode,omitempty"`                         // 0=NOERROR, 1=FORMERR, 2=SERVFAIL, 3=NXDOMAIN, etc.
	RcodeName string `protobuf:"bytes,2,opt,name=rcode_name,json=rcodeName,proto3" json:"rcode_name,omitempty"` // NOERROR, FORMERR, SERVFAIL, NXDOMAIN, etc.
	// Response sections
	Answer     []*ResourceRecord `protobuf:"bytes,3,rep,name=answer,proto3" json:"answer,omitempty"`
	Authority  []*ResourceRecord `protobuf:"bytes,4,rep,name=authority,proto3" json:"authority,omitempty"`
	Additional []*ResourceRecord `protobuf:"bytes,5,rep,name=additional,proto3" json:"additional,omitempty"`
	// Response flags
	Authoritative      bool `protobuf:"varint,6,opt,name=authoritative,proto3" json:"authoritative,omitempty"`
	Truncated          bool `protobuf:"varint,7,opt,name=truncated,proto3" json:"truncated,omitempty"`
	RecursionAvailable bool `protobuf:"varint,8,opt,name=recursion_available,json=recursionAvailable,proto3" json:"recursion_available,omitempty"`
	// Metadata
	Meta         *QueryMeta    `protobuf:"bytes,9,opt,name=meta,proto3" json:"meta,omitempty"`
	ResponseMeta *ResponseMeta `protobuf:"bytes,10,opt,name=response_meta,json=responseMeta,proto3" json:"response_meta,omitempty"`
	// DNSSEC validation info (if requested)
	Dnssec *DNSSECValidation `protobuf:"bytes,11,opt,name=dnssec,proto3" json:"dnssec,omitempty"`
	// Optional: wire format response
	WireFormat []byte `protobuf:"bytes,12,opt,name=wire_format,json=wireFormat,proto3" json:"wire_format,omitempty"`
	// Query that was answered (for streaming context)
	Request *QueryRequest `protobuf:"bytes,13,opt,name=request,proto3" json:"request,omitempty"`
	// Error information if present
	Error         *ErrorDetail `protobuf:"bytes,14,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_dns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetRcode() int32 {
	if x != nil {
		return x.Rcode
	}
	return 0
}

func (x *QueryResponse) GetRcodeName() string {
	if x != nil {
		return x.RcodeName
	}
	return ""
}

func (x *QueryResponse) GetAnswer() []*ResourceRecord {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *QueryResponse) GetAuthority() []*ResourceRecord {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *QueryResponse) GetAdditional() []*ResourceRecord {
	if x != nil {
		return x.Additional
	}
	return nil
}

func (x *QueryResponse) GetAuthoritative() bool {
	if x != nil {
		return x.Authoritative
	}
	return false
}

func (x *QueryResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *QueryResponse) GetRecursionAvailable() bool {
	if x != nil {
		return x.RecursionAvailable
	}
	return false
}

func (x *QueryResponse) GetMeta() *QueryMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *QueryResponse) GetResponseMeta() *ResponseMeta {
	if x != nil {
		return x.ResponseMeta
	}
	return nil
}

func (x *QueryResponse) GetDnssec() *DNSSECValidation {
	if x != nil {
		return x.Dnssec
	}
	return nil
}

func (x *QueryResponse) GetWireFormat() []byte {
	if x != nil {
		return x.WireFormat
	}
	return nil
}

func (x *QueryResponse) GetRequest() *QueryRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *QueryResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

// BatchQueryRequest for high-volume operations
type BatchQueryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Queries        []*QueryRequest        `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	FailOnError    bool                   `protobuf:"varint,2,opt,name=fail_on_error,json=failOnError,proto3" json:"fail_on_error,omitempty"` // Stop on first error or continue
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchQueryRequest) Reset() {
	*x = BatchQueryRequest{}
	mi := &file_dns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchQueryRequest) ProtoMessage() {}

func (x *BatchQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchQueryRequest.ProtoReflect.Descriptor instead.
func (*BatchQueryRequest) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{2}
}

func (x *BatchQueryRequest) GetQueries() []*QueryRequest {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *BatchQueryRequest) GetFailOnError() bool {
	if x != nil {
		return x.FailOnError
	}
	return false
}

func (x *BatchQueryRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// BatchQueryResponse for high-volume operations
type BatchQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*QueryResponse       `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Successful    int32                  `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	TotalTime     *durationpb.Duration   `protobuf:"bytes,4,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	Errors        []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchQueryResponse) Reset() {
	*x = BatchQueryResponse{}
	mi := &file_dns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchQueryResponse) ProtoMessage() {}

func (x *BatchQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchQueryResponse.ProtoReflect.Descriptor instead.
func (*BatchQueryResponse) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{3}
}

func (x *BatchQueryResponse) GetResponses() []*QueryResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *BatchQueryResponse) GetSuccessful() int32 {
	if x != nil {
		return x.Successful
	}
	return 0
}

func (x *BatchQueryResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BatchQueryResponse) GetTotalTime() *durationpb.Duration {
	if x != nil {
		return x.TotalTime
	}
	return nil
}

func (x *BatchQueryResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

// QueryTrace for detailed resolution tracing
type QueryTrace struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	QueryName     string                  `protobuf:"bytes,1,opt,name=query_name,json=queryName,proto3" json:"query_name,omitempty"`
	QueryType     string                  `protobuf:"bytes,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	Steps         []*QueryTrace_TraceStep `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	Successful    bool                    `protobuf:"varint,4,opt,name=successful,proto3" json:"successful,omitempty"`
	ErrorMessage  string                  `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTrace) Reset() {
	*x = QueryTrace{}
	mi := &file_dns_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTrace) ProtoMessage() {}

func (x *QueryTrace) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTrace.ProtoReflect.Descriptor instead.
func (*QueryTrace) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{4}
}

func (x *QueryTrace) GetQueryName() string {
	if x != nil {
		return x.QueryName
	}
	return ""
}

func (x *QueryTrace) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *QueryTrace) GetSteps() []*QueryTrace_TraceStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *QueryTrace) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *QueryTrace) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type QueryTrace_TraceStep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Server         string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Query          *QueryRequest          `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Response       *QueryResponse         `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	Latency        *durationpb.Duration   `protobuf:"bytes,4,opt,name=latency,proto3" json:"latency,omitempty"`
	Cached         bool                   `protobuf:"varint,5,opt,name=cached,proto3" json:"cached,omitempty"`
	Dnssec         *DNSSECValidation      `protobuf:"bytes,6,opt,name=dnssec,proto3" json:"dnssec,omitempty"`
	RecursionDepth int32                  `protobuf:"varint,7,opt,name=recursion_depth,json=recursionDepth,proto3" json:"recursion_depth,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryTrace_TraceStep) Reset() {
	*x = QueryTrace_TraceStep{}
	mi := &file_dns_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTrace_TraceStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTrace_TraceStep) ProtoMessage() {}

func (x *QueryTrace_TraceStep) ProtoReflect() protoreflect.Message {
	mi := &file_dns_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTrace_TraceStep.ProtoReflect.Descriptor instead.
func (*QueryTrace_TraceStep) Descriptor() ([]byte, []int) {
	return file_dns_proto_rawDescGZIP(), []int{4, 0}
}

func (x *QueryTrace_TraceStep) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *QueryTrace_TraceStep) GetQuery() *QueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *QueryTrace_TraceStep) GetResponse() *QueryResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *QueryTrace_TraceStep) GetLatency() *durationpb.Duration {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *QueryTrace_TraceStep) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *QueryTrace_TraceStep) GetDnssec() *DNSSECValidation {
	if x != nil {
		return x.Dnssec
	}
	return nil
}

func (x *QueryTrace_TraceStep) GetRecursionDepth() int32 {
	if x != nil {
		return x.RecursionDepth
	}
	return 0
}

var File_dns_proto protoreflect.FileDescriptor

const file_dns_proto_rawDesc = "" +
	"\n" +
	"\tdns.proto\x12\rdnsscience.v1\x1a\fcommon.proto\x1a\x1egoogle/protobuf/duration.proto\"\xea\x02\n" +
	"\fQueryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x16\n" +
	"\x06dnssec\x18\x04 \x01(\bR\x06dnssec\x12+\n" +
	"\x11recursion_desired\x18\x05 \x01(\bR\x10recursionDesired\x12+\n" +
	"\x11checking_disabled\x18\x06 \x01(\bR\x10checkingDisabled\x12\x1b\n" +
	"\tserver_id\x18\a \x01(\tR\bserverId\x129\n" +
	"\x04tags\x18\b \x03(\v2%.dnsscience.v1.QueryRequest.TagsEntryR\x04tags\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x05\n" +
	"\rQueryResponse\x12\x14\n" +
	"\x05rcode\x18\x01 \x01(\x05R\x05rcode\x12\x1d\n" +
	"\n" +
	"rcode_name\x18\x02 \x01(\tR\trcodeName\x125\n" +
	"\x06answer\x18\x03 \x03(\v2\x1d.dnsscience.v1.ResourceRecordR\x06answer\x12;\n" +
	"\tauthority\x18\x04 \x03(\v2\x1d.dnsscience.v1.ResourceRecordR\tauthority\x12=\n" +
	"\n" +
	"additional\x18\x05 \x03(\v2\x1d.dnsscience.v1.ResourceRecordR\n" +
	"additional\x12$\n" +
	"\rauthoritative\x18\x06 \x01(\bR\rauthoritative\x12\x1c\n" +
	"\ttruncated\x18\a \x01(\bR\ttruncated\x12/\n" +
	"\x13recursion_available\x18\b \x01(\bR\x12recursionAvailable\x12,\n" +
	"\x04meta\x18\t \x01(\v2\x18.dnsscience.v1.QueryMetaR\x04meta\x12@\n" +
	"\rresponse_meta\x18\n" +
	" \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\fresponseMeta\x127\n" +
	"\x06dnssec\x18\v \x01(\v2\x1f.dnsscience.v1.DNSSECValidationR\x06dnssec\x12\x1f\n" +
	"\vwire_format\x18\f \x01(\fR\n" +
	"wireFormat\x125\n" +
	"\arequest\x18\r \x01(\v2\x1b.dnsscience.v1.QueryRequestR\arequest\x120\n" +
	"\x05error\x18\x0e \x01(\v2\x1a.dnsscience.v1.ErrorDetailR\x05error\"\x97\x01\n" +
	"\x11BatchQueryRequest\x125\n" +
	"\aqueries\x18\x01 \x03(\v2\x1b.dnsscience.v1.QueryRequestR\aqueries\x12\"\n" +
	"\rfail_on_error\x18\x02 \x01(\bR\vfailOnError\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"\xda\x01\n" +
	"\x12BatchQueryResponse\x12:\n" +
	"\tresponses\x18\x01 \x03(\v2\x1c.dnsscience.v1.QueryResponseR\tresponses\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\x05R\n" +
	"successful\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x128\n" +
	"\n" +
	"total_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\ttotalTime\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\"\x8c\x04\n" +
	"\n" +
	"QueryTrace\x12\x1d\n" +
	"\n" +
	"query_name\x18\x01 \x01(\tR\tqueryName\x12\x1d\n" +
	"\n" +
	"query_type\x18\x02 \x01(\tR\tqueryType\x129\n" +
	"\x05steps\x18\x03 \x03(\v2#.dnsscience.v1.QueryTrace.TraceStepR\x05steps\x12\x1e\n" +
	"\n" +
	"successful\x18\x04 \x01(\bR\n" +
	"successful\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x1a\xbf\x02\n" +
	"\tTraceStep\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x121\n" +
	"\x05query\x18\x02 \x01(\v2\x1b.dnsscience.v1.QueryRequestR\x05query\x128\n" +
	"\bresponse\x18\x03 \x01(\v2\x1c.dnsscience.v1.QueryResponseR\bresponse\x123\n" +
	"\alatency\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\alatency\x12\x16\n" +
	"\x06cached\x18\x05 \x01(\bR\x06cached\x127\n" +
	"\x06dnssec\x18\x06 \x01(\v2\x1f.dnsscience.v1.DNSSECValidationR\x06dnssec\x12'\n" +
	"\x0frecursion_depth\x18\a \x01(\x05R\x0erecursionDepth2\xf5\x01\n" +
	"\n" +
	"DNSService\x12B\n" +
	"\x05Query\x12\x1b.dnsscience.v1.QueryRequest\x1a\x1c.dnsscience.v1.QueryResponse\x12N\n" +
	"\rStreamQueries\x12\x1b.dnsscience.v1.QueryRequest\x1a\x1c.dnsscience.v1.QueryResponse(\x010\x01\x12S\n" +
	"\fBatchQueries\x12 .dnsscience.v1.BatchQueryRequest\x1a!.dnsscience.v1.BatchQueryResponseB5Z3github.com/dnsscience/dnsscienced/api/grpc/proto/pbb\x06proto3"

var (
	file_dns_proto_rawDescOnce sync.Once
	file_dns_proto_rawDescData []byte
)

func file_dns_proto_rawDescGZIP() []byte {
	file_dns_proto_rawDescOnce.Do(func() {
		file_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dns_proto_rawDesc), len(file_dns_proto_rawDesc)))
	})
	return file_dns_proto_rawDescData
}

var file_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dns_proto_goTypes = []any{
	(*QueryRequest)(nil),         // 0: dnsscience.v1.QueryRequest
	(*QueryResponse)(nil),        // 1: dnsscience.v1.QueryResponse
	(*BatchQueryRequest)(nil),    // 2: dnsscience.v1.BatchQueryRequest
	(*BatchQueryResponse)(nil),   // 3: dnsscience.v1.BatchQueryResponse
	(*QueryTrace)(nil),           // 4: dnsscience.v1.QueryTrace
	nil,                          // 5: dnsscience.v1.QueryRequest.TagsEntry
	(*QueryTrace_TraceStep)(nil), // 6: dnsscience.v1.QueryTrace.TraceStep
	(*ResourceRecord)(nil),       // 7: dnsscience.v1.ResourceRecord
	(*QueryMeta)(nil),            // 8: dnsscience.v1.QueryMeta
	(*ResponseMeta)(nil),         // 9: dnsscience.v1.ResponseMeta
	(*DNSSECValidation)(nil),     // 10: dnsscience.v1.DNSSECValidation
	(*ErrorDetail)(nil),          // 11: dnsscience.v1.ErrorDetail
	(*durationpb.Duration)(nil),  // 12: google.protobuf.Duration
}
var file_dns_proto_depIdxs = []int32{
	5,  // 0: dnsscience.v1.QueryRequest.tags:type_name -> dnsscience.v1.QueryRequest.TagsEntry
	7,  // 1: dnsscience.v1.QueryResponse.answer:type_name -> dnsscience.v1.ResourceRecord
	7,  // 2: dnsscience.v1.QueryResponse.authority:type_name -> dnsscience.v1.ResourceRecord
	7,  // 3: dnsscience.v1.QueryResponse.additional:type_name -> dnsscience.v1.ResourceRecord
	8,  // 4: dnsscience.v1.QueryResponse.meta:type_name -> dnsscience.v1.QueryMeta
	9,  // 5: dnsscience.v1.QueryResponse.response_meta:type_name -> dnsscience.v1.ResponseMeta
	10, // 6: dnsscience.v1.QueryResponse.dnssec:type_name -> dnsscience.v1.DNSSECValidation
	0,  // 7: dnsscience.v1.QueryResponse.request:type_name -> dnsscience.v1.QueryRequest
	11, // 8: dnsscience.v1.QueryResponse.error:type_name -> dnsscience.v1.ErrorDetail
	0,  // 9: dnsscience.v1.BatchQueryRequest.queries:type_name -> dnsscience.v1.QueryRequest
	1,  // 10: dnsscience.v1.BatchQueryResponse.responses:type_name -> dnsscience.v1.QueryResponse
	12, // 11: dnsscience.v1.BatchQueryResponse.total_time:type_name -> google.protobuf.Duration
	6,  // 12: dnsscience.v1.QueryTrace.steps:type_name -> dnsscience.v1.QueryTrace.TraceStep
	0,  // 13: dnsscience.v1.QueryTrace.TraceStep.query:type_name -> dnsscience.v1.QueryRequest
	1,  // 14: dnsscience.v1.QueryTrace.TraceStep.response:type_name -> dnsscience.v1.QueryResponse
	12, // 15: dnsscience.v1.QueryTrace.TraceStep.latency:type_name -> google.protobuf.Duration
	10, // 16: dnsscience.v1.QueryTrace.TraceStep.dnssec:type_name -> dnsscience.v1.DNSSECValidation
	0,  // 17: dnsscience.v1.DNSService.Query:input_type -> dnsscience.v1.QueryRequest
	0,  // 18: dnsscience.v1.DNSService.StreamQueries:input_type -> dnsscience.v1.QueryRequest
	2,  // 19: dnsscience.v1.DNSService.BatchQueries:input_type -> dnsscience.v1.BatchQueryRequest
	1,  // 20: dnsscience.v1.DNSService.Query:output_type -> dnsscience.v1.QueryResponse
	1,  // 21: dnsscience.v1.DNSService.StreamQueries:output_type -> dnsscience.v1.QueryResponse
	3,  // 22: dnsscience.v1.DNSService.BatchQueries:output_type -> dnsscience.v1.BatchQueryResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_dns_proto_init() }
func file_dns_proto_init() {
	if File_dns_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dns_proto_rawDesc), len(file_dns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dns_proto_goTypes,
		DependencyIndexes: file_dns_proto_depIdxs,
		MessageInfos:      file_dns_proto_msgTypes,
	}.Build()
	File_dns_proto = out.File
	file_dns_proto_goTypes = nil
	file_dns_proto_depIdxs = nil
}
