// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthStatus enumeration
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type HealthInfo_HealthCheck int32

const (
	HealthInfo_HEALTH_CHECK_UNSPECIFIED HealthInfo_HealthCheck = 0
	HealthInfo_HEALTH_CHECK_ZONES       HealthInfo_HealthCheck = 1
	HealthInfo_HEALTH_CHECK_DNSSEC      HealthInfo_HealthCheck = 2
	HealthInfo_HEALTH_CHECK_CACHE       HealthInfo_HealthCheck = 3
	HealthInfo_HEALTH_CHECK_NETWORK     HealthInfo_HealthCheck = 4
	HealthInfo_HEALTH_CHECK_STORAGE     HealthInfo_HealthCheck = 5
)

// Enum value maps for HealthInfo_HealthCheck.
var (
	HealthInfo_HealthCheck_name = map[int32]string{
		0: "HEALTH_CHECK_UNSPECIFIED",
		1: "HEALTH_CHECK_ZONES",
		2: "HEALTH_CHECK_DNSSEC",
		3: "HEALTH_CHECK_CACHE",
		4: "HEALTH_CHECK_NETWORK",
		5: "HEALTH_CHECK_STORAGE",
	}
	HealthInfo_HealthCheck_value = map[string]int32{
		"HEALTH_CHECK_UNSPECIFIED": 0,
		"HEALTH_CHECK_ZONES":       1,
		"HEALTH_CHECK_DNSSEC":      2,
		"HEALTH_CHECK_CACHE":       3,
		"HEALTH_CHECK_NETWORK":     4,
		"HEALTH_CHECK_STORAGE":     5,
	}
)

func (x HealthInfo_HealthCheck) Enum() *HealthInfo_HealthCheck {
	p := new(HealthInfo_HealthCheck)
	*p = x
	return p
}

func (x HealthInfo_HealthCheck) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthInfo_HealthCheck) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[1].Descriptor()
}

func (HealthInfo_HealthCheck) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[1]
}

func (x HealthInfo_HealthCheck) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthInfo_HealthCheck.Descriptor instead.
func (HealthInfo_HealthCheck) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1, 0}
}

type GetStatsRequest_TimePeriod int32

const (
	GetStatsRequest_TIME_PERIOD_UNSPECIFIED GetStatsRequest_TimePeriod = 0
	GetStatsRequest_TIME_PERIOD_1M          GetStatsRequest_TimePeriod = 1
	GetStatsRequest_TIME_PERIOD_5M          GetStatsRequest_TimePeriod = 2
	GetStatsRequest_TIME_PERIOD_1H          GetStatsRequest_TimePeriod = 3
	GetStatsRequest_TIME_PERIOD_24H         GetStatsRequest_TimePeriod = 4
	GetStatsRequest_TIME_PERIOD_7D          GetStatsRequest_TimePeriod = 5
)

// Enum value maps for GetStatsRequest_TimePeriod.
var (
	GetStatsRequest_TimePeriod_name = map[int32]string{
		0: "TIME_PERIOD_UNSPECIFIED",
		1: "TIME_PERIOD_1M",
		2: "TIME_PERIOD_5M",
		3: "TIME_PERIOD_1H",
		4: "TIME_PERIOD_24H",
		5: "TIME_PERIOD_7D",
	}
	GetStatsRequest_TimePeriod_value = map[string]int32{
		"TIME_PERIOD_UNSPECIFIED": 0,
		"TIME_PERIOD_1M":          1,
		"TIME_PERIOD_5M":          2,
		"TIME_PERIOD_1H":          3,
		"TIME_PERIOD_24H":         4,
		"TIME_PERIOD_7D":          5,
	}
)

func (x GetStatsRequest_TimePeriod) Enum() *GetStatsRequest_TimePeriod {
	p := new(GetStatsRequest_TimePeriod)
	*p = x
	return p
}

func (x GetStatsRequest_TimePeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetStatsRequest_TimePeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[2].Descriptor()
}

func (GetStatsRequest_TimePeriod) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[2]
}

func (x GetStatsRequest_TimePeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetStatsRequest_TimePeriod.Descriptor instead.
func (GetStatsRequest_TimePeriod) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6, 0}
}

type ServerStatusEvent_EventType int32

const (
	ServerStatusEvent_EVENT_TYPE_UNSPECIFIED         ServerStatusEvent_EventType = 0
	ServerStatusEvent_EVENT_TYPE_HEALTH_CHANGED      ServerStatusEvent_EventType = 1
	ServerStatusEvent_EVENT_TYPE_HIGH_MEMORY         ServerStatusEvent_EventType = 2
	ServerStatusEvent_EVENT_TYPE_HIGH_CPU            ServerStatusEvent_EventType = 3
	ServerStatusEvent_EVENT_TYPE_CONNECTION_LIMIT    ServerStatusEvent_EventType = 4
	ServerStatusEvent_EVENT_TYPE_DISK_SPACE_LOW      ServerStatusEvent_EventType = 5
	ServerStatusEvent_EVENT_TYPE_ZONE_LOAD_FAILED    ServerStatusEvent_EventType = 6
	ServerStatusEvent_EVENT_TYPE_DNSSEC_KEY_EXPIRING ServerStatusEvent_EventType = 7
)

// Enum value maps for ServerStatusEvent_EventType.
var (
	ServerStatusEvent_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_HEALTH_CHANGED",
		2: "EVENT_TYPE_HIGH_MEMORY",
		3: "EVENT_TYPE_HIGH_CPU",
		4: "EVENT_TYPE_CONNECTION_LIMIT",
		5: "EVENT_TYPE_DISK_SPACE_LOW",
		6: "EVENT_TYPE_ZONE_LOAD_FAILED",
		7: "EVENT_TYPE_DNSSEC_KEY_EXPIRING",
	}
	ServerStatusEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":         0,
		"EVENT_TYPE_HEALTH_CHANGED":      1,
		"EVENT_TYPE_HIGH_MEMORY":         2,
		"EVENT_TYPE_HIGH_CPU":            3,
		"EVENT_TYPE_CONNECTION_LIMIT":    4,
		"EVENT_TYPE_DISK_SPACE_LOW":      5,
		"EVENT_TYPE_ZONE_LOAD_FAILED":    6,
		"EVENT_TYPE_DNSSEC_KEY_EXPIRING": 7,
	}
)

func (x ServerStatusEvent_EventType) Enum() *ServerStatusEvent_EventType {
	p := new(ServerStatusEvent_EventType)
	*p = x
	return p
}

func (x ServerStatusEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatusEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[3].Descriptor()
}

func (ServerStatusEvent_EventType) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[3]
}

func (x ServerStatusEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatusEvent_EventType.Descriptor instead.
func (ServerStatusEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{21, 0}
}

// Server information
type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Daemon        string                 `protobuf:"bytes,3,opt,name=daemon,proto3" json:"daemon,omitempty"` // dnsscience-authd, dnsscience-cached
	UptimeSeconds int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Hostname      string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetDaemon() string {
	if x != nil {
		return x.Daemon
	}
	return ""
}

func (x *ServerInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServerInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ServerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

// Health information
type HealthInfo struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        HealthStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=dnsscience.v1.HealthStatus" json:"status,omitempty"`
	Checks        []*HealthInfo_CheckResult `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthInfo) Reset() {
	*x = HealthInfo{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthInfo) ProtoMessage() {}

func (x *HealthInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthInfo.ProtoReflect.Descriptor instead.
func (*HealthInfo) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *HealthInfo) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthInfo) GetChecks() []*HealthInfo_CheckResult {
	if x != nil {
		return x.Checks
	}
	return nil
}

// Resource usage information
type ResourceInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent          float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes         int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	MemoryPercent       float32                `protobuf:"fixed32,3,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	Goroutines          int32                  `protobuf:"varint,4,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	OpenFileDescriptors int32                  `protobuf:"varint,5,opt,name=open_file_descriptors,json=openFileDescriptors,proto3" json:"open_file_descriptors,omitempty"`
	MaxFileDescriptors  int32                  `protobuf:"varint,6,opt,name=max_file_descriptors,json=maxFileDescriptors,proto3" json:"max_file_descriptors,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceInfo) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceInfo) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceInfo) GetMemoryPercent() float32 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ResourceInfo) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *ResourceInfo) GetOpenFileDescriptors() int32 {
	if x != nil {
		return x.OpenFileDescriptors
	}
	return 0
}

func (x *ResourceInfo) GetMaxFileDescriptors() int32 {
	if x != nil {
		return x.MaxFileDescriptors
	}
	return 0
}

// Network connection statistics
type NetworkStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UdpConnections   int32                  `protobuf:"varint,1,opt,name=udp_connections,json=udpConnections,proto3" json:"udp_connections,omitempty"`
	TcpConnections   int32                  `protobuf:"varint,2,opt,name=tcp_connections,json=tcpConnections,proto3" json:"tcp_connections,omitempty"`
	TlsConnections   int32                  `protobuf:"varint,3,opt,name=tls_connections,json=tlsConnections,proto3" json:"tls_connections,omitempty"`
	HttpsConnections int32                  `protobuf:"varint,4,opt,name=https_connections,json=httpsConnections,proto3" json:"https_connections,omitempty"`
	QuicConnections  int32                  `protobuf:"varint,5,opt,name=quic_connections,json=quicConnections,proto3" json:"quic_connections,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkStats) GetUdpConnections() int32 {
	if x != nil {
		return x.UdpConnections
	}
	return 0
}

func (x *NetworkStats) GetTcpConnections() int32 {
	if x != nil {
		return x.TcpConnections
	}
	return 0
}

func (x *NetworkStats) GetTlsConnections() int32 {
	if x != nil {
		return x.TlsConnections
	}
	return 0
}

func (x *NetworkStats) GetHttpsConnections() int32 {
	if x != nil {
		return x.HttpsConnections
	}
	return 0
}

func (x *NetworkStats) GetQuicConnections() int32 {
	if x != nil {
		return x.QuicConnections
	}
	return 0
}

// GetStatusRequest
type GetStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncludeResources bool                   `protobuf:"varint,1,opt,name=include_resources,json=includeResources,proto3" json:"include_resources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusRequest) GetIncludeResources() bool {
	if x != nil {
		return x.IncludeResources
	}
	return false
}

// GetStatusResponse
type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *ServerInfo            `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Health        *HealthInfo            `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	Resources     *ResourceInfo          `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	Network       *NetworkStats          `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *GetStatusResponse) GetHealth() *HealthInfo {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *GetStatusResponse) GetResources() *ResourceInfo {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *GetStatusResponse) GetNetwork() *NetworkStats {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *GetStatusResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// GetStatsRequest
type GetStatsRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Period        GetStatsRequest_TimePeriod `protobuf:"varint,1,opt,name=period,proto3,enum=dnsscience.v1.GetStatsRequest_TimePeriod" json:"period,omitempty"`
	Breakdowns    []string                   `protobuf:"bytes,2,rep,name=breakdowns,proto3" json:"breakdowns,omitempty"` // type, rcode, transport, zone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatsRequest) GetPeriod() GetStatsRequest_TimePeriod {
	if x != nil {
		return x.Period
	}
	return GetStatsRequest_TIME_PERIOD_UNSPECIFIED
}

func (x *GetStatsRequest) GetBreakdowns() []string {
	if x != nil {
		return x.Breakdowns
	}
	return nil
}

// Query statistics
type QueryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PerSecond     float64                `protobuf:"fixed64,2,opt,name=per_second,json=perSecond,proto3" json:"per_second,omitempty"`
	ByType        map[string]int64       `protobuf:"bytes,3,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`                // A, AAAA, MX, etc.
	ByRcode       map[string]int64       `protobuf:"bytes,4,rep,name=by_rcode,json=byRcode,proto3" json:"by_rcode,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`             // NOERROR, NXDOMAIN, etc.
	ByTransport   map[string]int64       `protobuf:"bytes,5,rep,name=by_transport,json=byTransport,proto3" json:"by_transport,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // udp, tcp, dot, doh, doq
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStats) Reset() {
	*x = QueryStats{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStats) ProtoMessage() {}

func (x *QueryStats) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStats.ProtoReflect.Descriptor instead.
func (*QueryStats) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *QueryStats) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryStats) GetPerSecond() float64 {
	if x != nil {
		return x.PerSecond
	}
	return 0
}

func (x *QueryStats) GetByType() map[string]int64 {
	if x != nil {
		return x.ByType
	}
	return nil
}

func (x *QueryStats) GetByRcode() map[string]int64 {
	if x != nil {
		return x.ByRcode
	}
	return nil
}

func (x *QueryStats) GetByTransport() map[string]int64 {
	if x != nil {
		return x.ByTransport
	}
	return nil
}

// Latency statistics
type LatencyStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvgMs         float64                `protobuf:"fixed64,1,opt,name=avg_ms,json=avgMs,proto3" json:"avg_ms,omitempty"`
	P50Ms         float64                `protobuf:"fixed64,2,opt,name=p50_ms,json=p50Ms,proto3" json:"p50_ms,omitempty"`
	P95Ms         float64                `protobuf:"fixed64,3,opt,name=p95_ms,json=p95Ms,proto3" json:"p95_ms,omitempty"`
	P99Ms         float64                `protobuf:"fixed64,4,opt,name=p99_ms,json=p99Ms,proto3" json:"p99_ms,omitempty"`
	MaxMs         float64                `protobuf:"fixed64,5,opt,name=max_ms,json=maxMs,proto3" json:"max_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyStats) Reset() {
	*x = LatencyStats{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyStats) ProtoMessage() {}

func (x *LatencyStats) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyStats.ProtoReflect.Descriptor instead.
func (*LatencyStats) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *LatencyStats) GetAvgMs() float64 {
	if x != nil {
		return x.AvgMs
	}
	return 0
}

func (x *LatencyStats) GetP50Ms() float64 {
	if x != nil {
		return x.P50Ms
	}
	return 0
}

func (x *LatencyStats) GetP95Ms() float64 {
	if x != nil {
		return x.P95Ms
	}
	return 0
}

func (x *LatencyStats) GetP99Ms() float64 {
	if x != nil {
		return x.P99Ms
	}
	return 0
}

func (x *LatencyStats) GetMaxMs() float64 {
	if x != nil {
		return x.MaxMs
	}
	return 0
}

// DNSSEC statistics
type DNSSECStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidationsTotal int64                  `protobuf:"varint,1,opt,name=validations_total,json=validationsTotal,proto3" json:"validations_total,omitempty"`
	Secure           int64                  `protobuf:"varint,2,opt,name=secure,proto3" json:"secure,omitempty"`
	Insecure         int64                  `protobuf:"varint,3,opt,name=insecure,proto3" json:"insecure,omitempty"`
	Bogus            int64                  `protobuf:"varint,4,opt,name=bogus,proto3" json:"bogus,omitempty"`
	Indeterminate    int64                  `protobuf:"varint,5,opt,name=indeterminate,proto3" json:"indeterminate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DNSSECStats) Reset() {
	*x = DNSSECStats{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSSECStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSSECStats) ProtoMessage() {}

func (x *DNSSECStats) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSSECStats.ProtoReflect.Descriptor instead.
func (*DNSSECStats) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *DNSSECStats) GetValidationsTotal() int64 {
	if x != nil {
		return x.ValidationsTotal
	}
	return 0
}

func (x *DNSSECStats) GetSecure() int64 {
	if x != nil {
		return x.Secure
	}
	return 0
}

func (x *DNSSECStats) GetInsecure() int64 {
	if x != nil {
		return x.Insecure
	}
	return 0
}

func (x *DNSSECStats) GetBogus() int64 {
	if x != nil {
		return x.Bogus
	}
	return 0
}

func (x *DNSSECStats) GetIndeterminate() int64 {
	if x != nil {
		return x.Indeterminate
	}
	return 0
}

// GetStatsResponse
type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	MeasuredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"`
	Queries       *QueryStats            `protobuf:"bytes,3,opt,name=queries,proto3" json:"queries,omitempty"`
	Latency       *LatencyStats          `protobuf:"bytes,4,opt,name=latency,proto3" json:"latency,omitempty"`
	Cache         *CacheStats            `protobuf:"bytes,5,opt,name=cache,proto3" json:"cache,omitempty"`
	Dnssec        *DNSSECStats           `protobuf:"bytes,6,opt,name=dnssec,proto3" json:"dnssec,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *GetStatsResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetStatsResponse) GetMeasuredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MeasuredAt
	}
	return nil
}

func (x *GetStatsResponse) GetQueries() *QueryStats {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *GetStatsResponse) GetLatency() *LatencyStats {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *GetStatsResponse) GetCache() *CacheStats {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *GetStatsResponse) GetDnssec() *DNSSECStats {
	if x != nil {
		return x.Dnssec
	}
	return nil
}

func (x *GetStatsResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// ReloadRequest
type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []string               `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"` // zones, acl, config, all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *ReloadRequest) GetSections() []string {
	if x != nil {
		return x.Sections
	}
	return nil
}

// ReloadResponse
type ReloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DurationMs    int32                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Reloaded      []string               `protobuf:"bytes,4,rep,name=reloaded,proto3" json:"reloaded,omitempty"`
	Errors        []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *ReloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReloadResponse) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ReloadResponse) GetReloaded() []string {
	if x != nil {
		return x.Reloaded
	}
	return nil
}

func (x *ReloadResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ReloadResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// ShutdownRequest
type ShutdownRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimeoutSeconds int32                  `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Default: 30
	Force          bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *ShutdownRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ShutdownRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// ShutdownResponse
type ShutdownResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Message               string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	GracefulPeriodSeconds int32                  `protobuf:"varint,2,opt,name=graceful_period_seconds,json=gracefulPeriodSeconds,proto3" json:"graceful_period_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{14}
}

func (x *ShutdownResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShutdownResponse) GetGracefulPeriodSeconds() int32 {
	if x != nil {
		return x.GracefulPeriodSeconds
	}
	return 0
}

// GetConfigRequest
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       string                 `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`                                   // global, zones, security, etc. (optional)
	RedactSecrets bool                   `protobuf:"varint,2,opt,name=redact_secrets,json=redactSecrets,proto3" json:"redact_secrets,omitempty"` // Default: true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{15}
}

func (x *GetConfigRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *GetConfigRequest) GetRedactSecrets() bool {
	if x != nil {
		return x.RedactSecrets
	}
	return false
}

// GetConfigResponse
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // JSON-encoded config sections
	Meta          *ResponseMeta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{16}
}

func (x *GetConfigResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// License information
type LicenseInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Product         string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Licensee        string                 `protobuf:"bytes,3,opt,name=licensee,proto3" json:"licensee,omitempty"`
	IssuedAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IsValid         bool                   `protobuf:"varint,6,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	DaysUntilExpiry int32                  `protobuf:"varint,7,opt,name=days_until_expiry,json=daysUntilExpiry,proto3" json:"days_until_expiry,omitempty"`
	Features        []string               `protobuf:"bytes,8,rep,name=features,proto3" json:"features,omitempty"`
	Serial          string                 `protobuf:"bytes,9,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LicenseInfo) Reset() {
	*x = LicenseInfo{}
	mi := &file_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseInfo) ProtoMessage() {}

func (x *LicenseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseInfo.ProtoReflect.Descriptor instead.
func (*LicenseInfo) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{17}
}

func (x *LicenseInfo) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *LicenseInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LicenseInfo) GetLicensee() string {
	if x != nil {
		return x.Licensee
	}
	return ""
}

func (x *LicenseInfo) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *LicenseInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *LicenseInfo) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *LicenseInfo) GetDaysUntilExpiry() int32 {
	if x != nil {
		return x.DaysUntilExpiry
	}
	return 0
}

func (x *LicenseInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *LicenseInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

// GetLicenseRequest
type GetLicenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLicenseRequest) Reset() {
	*x = GetLicenseRequest{}
	mi := &file_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLicenseRequest) ProtoMessage() {}

func (x *GetLicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLicenseRequest.ProtoReflect.Descriptor instead.
func (*GetLicenseRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{18}
}

// GetLicenseResponse
type GetLicenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	License       *LicenseInfo           `protobuf:"bytes,1,opt,name=license,proto3" json:"license,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLicenseResponse) Reset() {
	*x = GetLicenseResponse{}
	mi := &file_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLicenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLicenseResponse) ProtoMessage() {}

func (x *GetLicenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLicenseResponse.ProtoReflect.Descriptor instead.
func (*GetLicenseResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{19}
}

func (x *GetLicenseResponse) GetLicense() *LicenseInfo {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *GetLicenseResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// WatchStatusRequest for status streaming
type WatchStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // health_changed, memory_high, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStatusRequest) Reset() {
	*x = WatchStatusRequest{}
	mi := &file_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStatusRequest) ProtoMessage() {}

func (x *WatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{20}
}

func (x *WatchStatusRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

// ServerStatusEvent represents a status change event
type ServerStatusEvent struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          ServerStatusEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=dnsscience.v1.ServerStatusEvent_EventType" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Severity      HealthStatus                `protobuf:"varint,4,opt,name=severity,proto3,enum=dnsscience.v1.HealthStatus" json:"severity,omitempty"`
	Details       map[string]string           `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusEvent) Reset() {
	*x = ServerStatusEvent{}
	mi := &file_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusEvent) ProtoMessage() {}

func (x *ServerStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusEvent.ProtoReflect.Descriptor instead.
func (*ServerStatusEvent) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{21}
}

func (x *ServerStatusEvent) GetType() ServerStatusEvent_EventType {
	if x != nil {
		return x.Type
	}
	return ServerStatusEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *ServerStatusEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ServerStatusEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerStatusEvent) GetSeverity() HealthStatus {
	if x != nil {
		return x.Severity
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *ServerStatusEvent) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// GetMetricsRequest
type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"` // prometheus, json (default: prometheus)
	Labels        []string               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"` // Optional: filter by labels
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_server_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{22}
}

func (x *GetMetricsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetMetricsRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// GetMetricsResponse
type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Prometheus text format or JSON
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_server_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{23}
}

func (x *GetMetricsResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetMetricsResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetMetricsResponse) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *GetMetricsResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type HealthInfo_CheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Check         HealthInfo_HealthCheck `protobuf:"varint,1,opt,name=check,proto3,enum=dnsscience.v1.HealthInfo_HealthCheck" json:"check,omitempty"`
	Status        HealthStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=dnsscience.v1.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCount    int32                  `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthInfo_CheckResult) Reset() {
	*x = HealthInfo_CheckResult{}
	mi := &file_server_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthInfo_CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthInfo_CheckResult) ProtoMessage() {}

func (x *HealthInfo_CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthInfo_CheckResult.ProtoReflect.Descriptor instead.
func (*HealthInfo_CheckResult) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1, 0}
}

func (x *HealthInfo_CheckResult) GetCheck() HealthInfo_HealthCheck {
	if x != nil {
		return x.Check
	}
	return HealthInfo_HEALTH_CHECK_UNSPECIFIED
}

func (x *HealthInfo_CheckResult) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthInfo_CheckResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthInfo_CheckResult) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\rdnsscience.v1\x1a\fcommon.proto\x1a\vcache.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x01\n" +
	"\n" +
	"ServerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06daemon\x18\x03 \x01(\tR\x06daemon\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\"\xe8\x03\n" +
	"\n" +
	"HealthInfo\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.dnsscience.v1.HealthStatusR\x06status\x12=\n" +
	"\x06checks\x18\x02 \x03(\v2%.dnsscience.v1.HealthInfo.CheckResultR\x06checks\x1a\xba\x01\n" +
	"\vCheckResult\x12;\n" +
	"\x05check\x18\x01 \x01(\x0e2%.dnsscience.v1.HealthInfo.HealthCheckR\x05check\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.dnsscience.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x05R\n" +
	"errorCount\"\xa8\x01\n" +
	"\vHealthCheck\x12\x1c\n" +
	"\x18HEALTH_CHECK_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12HEALTH_CHECK_ZONES\x10\x01\x12\x17\n" +
	"\x13HEALTH_CHECK_DNSSEC\x10\x02\x12\x16\n" +
	"\x12HEALTH_CHECK_CACHE\x10\x03\x12\x18\n" +
	"\x14HEALTH_CHECK_NETWORK\x10\x04\x12\x18\n" +
	"\x14HEALTH_CHECK_STORAGE\x10\x05\"\xff\x01\n" +
	"\fResourceInfo\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12%\n" +
	"\x0ememory_percent\x18\x03 \x01(\x02R\rmemoryPercent\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x04 \x01(\x05R\n" +
	"goroutines\x122\n" +
	"\x15open_file_descriptors\x18\x05 \x01(\x05R\x13openFileDescriptors\x120\n" +
	"\x14max_file_descriptors\x18\x06 \x01(\x05R\x12maxFileDescriptors\"\xe1\x01\n" +
	"\fNetworkStats\x12'\n" +
	"\x0fudp_connections\x18\x01 \x01(\x05R\x0eudpConnections\x12'\n" +
	"\x0ftcp_connections\x18\x02 \x01(\x05R\x0etcpConnections\x12'\n" +
	"\x0ftls_connections\x18\x03 \x01(\x05R\x0etlsConnections\x12+\n" +
	"\x11https_connections\x18\x04 \x01(\x05R\x10httpsConnections\x12)\n" +
	"\x10quic_connections\x18\x05 \x01(\x05R\x0fquicConnections\"?\n" +
	"\x10GetStatusRequest\x12+\n" +
	"\x11include_resources\x18\x01 \x01(\bR\x10includeResources\"\x9c\x02\n" +
	"\x11GetStatusResponse\x121\n" +
	"\x06server\x18\x01 \x01(\v2\x19.dnsscience.v1.ServerInfoR\x06server\x121\n" +
	"\x06health\x18\x02 \x01(\v2\x19.dnsscience.v1.HealthInfoR\x06health\x129\n" +
	"\tresources\x18\x03 \x01(\v2\x1b.dnsscience.v1.ResourceInfoR\tresources\x125\n" +
	"\anetwork\x18\x04 \x01(\v2\x1b.dnsscience.v1.NetworkStatsR\anetwork\x12/\n" +
	"\x04meta\x18\x05 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"\x85\x02\n" +
	"\x0fGetStatsRequest\x12A\n" +
	"\x06period\x18\x01 \x01(\x0e2).dnsscience.v1.GetStatsRequest.TimePeriodR\x06period\x12\x1e\n" +
	"\n" +
	"breakdowns\x18\x02 \x03(\tR\n" +
	"breakdowns\"\x8e\x01\n" +
	"\n" +
	"TimePeriod\x12\x1b\n" +
	"\x17TIME_PERIOD_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTIME_PERIOD_1M\x10\x01\x12\x12\n" +
	"\x0eTIME_PERIOD_5M\x10\x02\x12\x12\n" +
	"\x0eTIME_PERIOD_1H\x10\x03\x12\x13\n" +
	"\x0fTIME_PERIOD_24H\x10\x04\x12\x12\n" +
	"\x0eTIME_PERIOD_7D\x10\x05\"\xca\x03\n" +
	"\n" +
	"QueryStats\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"per_second\x18\x02 \x01(\x01R\tperSecond\x12>\n" +
	"\aby_type\x18\x03 \x03(\v2%.dnsscience.v1.QueryStats.ByTypeEntryR\x06byType\x12A\n" +
	"\bby_rcode\x18\x04 \x03(\v2&.dnsscience.v1.QueryStats.ByRcodeEntryR\abyRcode\x12M\n" +
	"\fby_transport\x18\x05 \x03(\v2*.dnsscience.v1.QueryStats.ByTransportEntryR\vbyTransport\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a:\n" +
	"\fByRcodeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10ByTransportEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x81\x01\n" +
	"\fLatencyStats\x12\x15\n" +
	"\x06avg_ms\x18\x01 \x01(\x01R\x05avgMs\x12\x15\n" +
	"\x06p50_ms\x18\x02 \x01(\x01R\x05p50Ms\x12\x15\n" +
	"\x06p95_ms\x18\x03 \x01(\x01R\x05p95Ms\x12\x15\n" +
	"\x06p99_ms\x18\x04 \x01(\x01R\x05p99Ms\x12\x15\n" +
	"\x06max_ms\x18\x05 \x01(\x01R\x05maxMs\"\xaa\x01\n" +
	"\vDNSSECStats\x12+\n" +
	"\x11validations_total\x18\x01 \x01(\x03R\x10validationsTotal\x12\x16\n" +
	"\x06secure\x18\x02 \x01(\x03R\x06secure\x12\x1a\n" +
	"\binsecure\x18\x03 \x01(\x03R\binsecure\x12\x14\n" +
	"\x05bogus\x18\x04 \x01(\x03R\x05bogus\x12$\n" +
	"\rindeterminate\x18\x05 \x01(\x03R\rindeterminate\"\xe9\x02\n" +
	"\x10GetStatsResponse\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12;\n" +
	"\vmeasured_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"measuredAt\x123\n" +
	"\aqueries\x18\x03 \x01(\v2\x19.dnsscience.v1.QueryStatsR\aqueries\x125\n" +
	"\alatency\x18\x04 \x01(\v2\x1b.dnsscience.v1.LatencyStatsR\alatency\x12/\n" +
	"\x05cache\x18\x05 \x01(\v2\x19.dnsscience.v1.CacheStatsR\x05cache\x122\n" +
	"\x06dnssec\x18\x06 \x01(\v2\x1a.dnsscience.v1.DNSSECStatsR\x06dnssec\x12/\n" +
	"\x04meta\x18\a \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"+\n" +
	"\rReloadRequest\x12\x1a\n" +
	"\bsections\x18\x01 \x03(\tR\bsections\"\xca\x01\n" +
	"\x0eReloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x05R\n" +
	"durationMs\x12\x1a\n" +
	"\breloaded\x18\x04 \x03(\tR\breloaded\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\x12/\n" +
	"\x04meta\x18\x06 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"P\n" +
	"\x0fShutdownRequest\x12'\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x05R\x0etimeoutSeconds\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"d\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x126\n" +
	"\x17graceful_period_seconds\x18\x02 \x01(\x05R\x15gracefulPeriodSeconds\"S\n" +
	"\x10GetConfigRequest\x12\x18\n" +
	"\asection\x18\x01 \x01(\tR\asection\x12%\n" +
	"\x0eredact_secrets\x18\x02 \x01(\bR\rredactSecrets\"\xc5\x01\n" +
	"\x11GetConfigResponse\x12D\n" +
	"\x06config\x18\x01 \x03(\v2,.dnsscience.v1.GetConfigResponse.ConfigEntryR\x06config\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x02\n" +
	"\vLicenseInfo\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\blicensee\x18\x03 \x01(\tR\blicensee\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x19\n" +
	"\bis_valid\x18\x06 \x01(\bR\aisValid\x12*\n" +
	"\x11days_until_expiry\x18\a \x01(\x05R\x0fdaysUntilExpiry\x12\x1a\n" +
	"\bfeatures\x18\b \x03(\tR\bfeatures\x12\x16\n" +
	"\x06serial\x18\t \x01(\tR\x06serial\"\x13\n" +
	"\x11GetLicenseRequest\"{\n" +
	"\x12GetLicenseResponse\x124\n" +
	"\alicense\x18\x01 \x01(\v2\x1a.dnsscience.v1.LicenseInfoR\alicense\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"5\n" +
	"\x12WatchStatusRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\xe8\x04\n" +
	"\x11ServerStatusEvent\x12>\n" +
	"\x04type\x18\x01 \x01(\x0e2*.dnsscience.v1.ServerStatusEvent.EventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x127\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1b.dnsscience.v1.HealthStatusR\bseverity\x12G\n" +
	"\adetails\x18\x05 \x03(\v2-.dnsscience.v1.ServerStatusEvent.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19EVENT_TYPE_HEALTH_CHANGED\x10\x01\x12\x1a\n" +
	"\x16EVENT_TYPE_HIGH_MEMORY\x10\x02\x12\x17\n" +
	"\x13EVENT_TYPE_HIGH_CPU\x10\x03\x12\x1f\n" +
	"\x1bEVENT_TYPE_CONNECTION_LIMIT\x10\x04\x12\x1d\n" +
	"\x19EVENT_TYPE_DISK_SPACE_LOW\x10\x05\x12\x1f\n" +
	"\x1bEVENT_TYPE_ZONE_LOAD_FAILED\x10\x06\x12\"\n" +
	"\x1eEVENT_TYPE_DNSSEC_KEY_EXPIRING\x10\a\"C\n" +
	"\x11GetMetricsRequest\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\tR\x06labels\"\xb6\x01\n" +
	"\x12GetMetricsResponse\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12=\n" +
	"\fcollected_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12/\n" +
	"\x04meta\x18\x04 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta*\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x032\x8c\x05\n" +
	"\rServerService\x12N\n" +
	"\tGetStatus\x12\x1f.dnsscience.v1.GetStatusRequest\x1a .dnsscience.v1.GetStatusResponse\x12K\n" +
	"\bGetStats\x12\x1e.dnsscience.v1.GetStatsRequest\x1a\x1f.dnsscience.v1.GetStatsResponse\x12E\n" +
	"\x06Reload\x12\x1c.dnsscience.v1.ReloadRequest\x1a\x1d.dnsscience.v1.ReloadResponse\x12K\n" +
	"\bShutdown\x12\x1e.dnsscience.v1.ShutdownRequest\x1a\x1f.dnsscience.v1.ShutdownResponse\x12N\n" +
	"\tGetConfig\x12\x1f.dnsscience.v1.GetConfigRequest\x1a .dnsscience.v1.GetConfigResponse\x12Q\n" +
	"\n" +
	"GetLicense\x12 .dnsscience.v1.GetLicenseRequest\x1a!.dnsscience.v1.GetLicenseResponse\x12T\n" +
	"\vWatchStatus\x12!.dnsscience.v1.WatchStatusRequest\x1a .dnsscience.v1.ServerStatusEvent0\x01\x12Q\n" +
	"\n" +
	"GetMetrics\x12 .dnsscience.v1.GetMetricsRequest\x1a!.dnsscience.v1.GetMetricsResponseB5Z3github.com/dnsscience/dnsscienced/api/grpc/proto/pbb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_server_proto_goTypes = []any{
	(HealthStatus)(0),                // 0: dnsscience.v1.HealthStatus
	(HealthInfo_HealthCheck)(0),      // 1: dnsscience.v1.HealthInfo.HealthCheck
	(GetStatsRequest_TimePeriod)(0),  // 2: dnsscience.v1.GetStatsRequest.TimePeriod
	(ServerStatusEvent_EventType)(0), // 3: dnsscience.v1.ServerStatusEvent.EventType
	(*ServerInfo)(nil),               // 4: dnsscience.v1.ServerInfo
	(*HealthInfo)(nil),               // 5: dnsscience.v1.HealthInfo
	(*ResourceInfo)(nil),             // 6: dnsscience.v1.ResourceInfo
	(*NetworkStats)(nil),             // 7: dnsscience.v1.NetworkStats
	(*GetStatusRequest)(nil),         // 8: dnsscience.v1.GetStatusRequest
	(*GetStatusResponse)(nil),        // 9: dnsscience.v1.GetStatusResponse
	(*GetStatsRequest)(nil),          // 10: dnsscience.v1.GetStatsRequest
	(*QueryStats)(nil),               // 11: dnsscience.v1.QueryStats
	(*LatencyStats)(nil),             // 12: dnsscience.v1.LatencyStats
	(*DNSSECStats)(nil),              // 13: dnsscience.v1.DNSSECStats
	(*GetStatsResponse)(nil),         // 14: dnsscience.v1.GetStatsResponse
	(*ReloadRequest)(nil),            // 15: dnsscience.v1.ReloadRequest
	(*ReloadResponse)(nil),           // 16: dnsscience.v1.ReloadResponse
	(*ShutdownRequest)(nil),          // 17: dnsscience.v1.ShutdownRequest
	(*ShutdownResponse)(nil),         // 18: dnsscience.v1.ShutdownResponse
	(*GetConfigRequest)(nil),         // 19: dnsscience.v1.GetConfigRequest
	(*GetConfigResponse)(nil),        // 20: dnsscience.v1.GetConfigResponse
	(*LicenseInfo)(nil),              // 21: dnsscience.v1.LicenseInfo
	(*GetLicenseRequest)(nil),        // 22: dnsscience.v1.GetLicenseRequest
	(*GetLicenseResponse)(nil),       // 23: dnsscience.v1.GetLicenseResponse
	(*WatchStatusRequest)(nil),       // 24: dnsscience.v1.WatchStatusRequest
	(*ServerStatusEvent)(nil),        // 25: dnsscience.v1.ServerStatusEvent
	(*GetMetricsRequest)(nil),        // 26: dnsscience.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),       // 27: dnsscience.v1.GetMetricsResponse
	(*HealthInfo_CheckResult)(nil),   // 28: dnsscience.v1.HealthInfo.CheckResult
	nil,                              // 29: dnsscience.v1.QueryStats.ByTypeEntry
	nil,                              // 30: dnsscience.v1.QueryStats.ByRcodeEntry
	nil,                              // 31: dnsscience.v1.QueryStats.ByTransportEntry
	nil,                              // 32: dnsscience.v1.GetConfigResponse.ConfigEntry
	nil,                              // 33: dnsscience.v1.ServerStatusEvent.DetailsEntry
	(*timestamppb.Timestamp)(nil),    // 34: google.protobuf.Timestamp
	(*ResponseMeta)(nil),             // 35: dnsscience.v1.ResponseMeta
	(*CacheStats)(nil),               // 36: dnsscience.v1.CacheStats
}
var file_server_proto_depIdxs = []int32{
	34, // 0: dnsscience.v1.ServerInfo.started_at:type_name -> google.protobuf.Timestamp
	0,  // 1: dnsscience.v1.HealthInfo.status:type_name -> dnsscience.v1.HealthStatus
	28, // 2: dnsscience.v1.HealthInfo.checks:type_name -> dnsscience.v1.HealthInfo.CheckResult
	4,  // 3: dnsscience.v1.GetStatusResponse.server:type_name -> dnsscience.v1.ServerInfo
	5,  // 4: dnsscience.v1.GetStatusResponse.health:type_name -> dnsscience.v1.HealthInfo
	6,  // 5: dnsscience.v1.GetStatusResponse.resources:type_name -> dnsscience.v1.ResourceInfo
	7,  // 6: dnsscience.v1.GetStatusResponse.network:type_name -> dnsscience.v1.NetworkStats
	35, // 7: dnsscience.v1.GetStatusResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	2,  // 8: dnsscience.v1.GetStatsRequest.period:type_name -> dnsscience.v1.GetStatsRequest.TimePeriod
	29, // 9: dnsscience.v1.QueryStats.by_type:type_name -> dnsscience.v1.QueryStats.ByTypeEntry
	30, // 10: dnsscience.v1.QueryStats.by_rcode:type_name -> dnsscience.v1.QueryStats.ByRcodeEntry
	31, // 11: dnsscience.v1.QueryStats.by_transport:type_name -> dnsscience.v1.QueryStats.ByTransportEntry
	34, // 12: dnsscience.v1.GetStatsResponse.measured_at:type_name -> google.protobuf.Timestamp
	11, // 13: dnsscience.v1.GetStatsResponse.queries:type_name -> dnsscience.v1.QueryStats
	12, // 14: dnsscience.v1.GetStatsResponse.latency:type_name -> dnsscience.v1.LatencyStats
	36, // 15: dnsscience.v1.GetStatsResponse.cache:type_name -> dnsscience.v1.CacheStats
	13, // 16: dnsscience.v1.GetStatsResponse.dnssec:type_name -> dnsscience.v1.DNSSECStats
	35, // 17: dnsscience.v1.GetStatsResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	35, // 18: dnsscience.v1.ReloadResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	32, // 19: dnsscience.v1.GetConfigResponse.config:type_name -> dnsscience.v1.GetConfigResponse.ConfigEntry
	35, // 20: dnsscience.v1.GetConfigResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	34, // 21: dnsscience.v1.LicenseInfo.issued_at:type_name -> google.protobuf.Timestamp
	34, // 22: dnsscience.v1.LicenseInfo.expires_at:type_name -> google.protobuf.Timestamp
	21, // 23: dnsscience.v1.GetLicenseResponse.license:type_name -> dnsscience.v1.LicenseInfo
	35, // 24: dnsscience.v1.GetLicenseResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	3,  // 25: dnsscience.v1.ServerStatusEvent.type:type_name -> dnsscience.v1.ServerStatusEvent.EventType
	34, // 26: dnsscience.v1.ServerStatusEvent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 27: dnsscience.v1.ServerStatusEvent.severity:type_name -> dnsscience.v1.HealthStatus
	33, // 28: dnsscience.v1.ServerStatusEvent.details:type_name -> dnsscience.v1.ServerStatusEvent.DetailsEntry
	34, // 29: dnsscience.v1.GetMetricsResponse.collected_at:type_name -> google.protobuf.Timestamp
	35, // 30: dnsscience.v1.GetMetricsResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	1,  // 31: dnsscience.v1.HealthInfo.CheckResult.check:type_name -> dnsscience.v1.HealthInfo.HealthCheck
	0,  // 32: dnsscience.v1.HealthInfo.CheckResult.status:type_name -> dnsscience.v1.HealthStatus
	8,  // 33: dnsscience.v1.ServerService.GetStatus:input_type -> dnsscience.v1.GetStatusRequest
	10, // 34: dnsscience.v1.ServerService.GetStats:input_type -> dnsscience.v1.GetStatsRequest
	15, // 35: dnsscience.v1.ServerService.Reload:input_type -> dnsscience.v1.ReloadRequest
	17, // 36: dnsscience.v1.ServerService.Shutdown:input_type -> dnsscience.v1.ShutdownRequest
	19, // 37: dnsscience.v1.ServerService.GetConfig:input_type -> dnsscience.v1.GetConfigRequest
	22, // 38: dnsscience.v1.ServerService.GetLicense:input_type -> dnsscience.v1.GetLicenseRequest
	24, // 39: dnsscience.v1.ServerService.WatchStatus:input_type -> dnsscience.v1.WatchStatusRequest
	26, // 40: dnsscience.v1.ServerService.GetMetrics:input_type -> dnsscience.v1.GetMetricsRequest
	9,  // 41: dnsscience.v1.ServerService.GetStatus:output_type -> dnsscience.v1.GetStatusResponse
	14, // 42: dnsscience.v1.ServerService.GetStats:output_type -> dnsscience.v1.GetStatsResponse
	16, // 43: dnsscience.v1.ServerService.Reload:output_type -> dnsscience.v1.ReloadResponse
	18, // 44: dnsscience.v1.ServerService.Shutdown:output_type -> dnsscience.v1.ShutdownResponse
	20, // 45: dnsscience.v1.ServerService.GetConfig:output_type -> dnsscience.v1.GetConfigResponse
	23, // 46: dnsscience.v1.ServerService.GetLicense:output_type -> dnsscience.v1.GetLicenseResponse
	25, // 47: dnsscience.v1.ServerService.WatchStatus:output_type -> dnsscience.v1.ServerStatusEvent
	27, // 48: dnsscience.v1.ServerService.GetMetrics:output_type -> dnsscience.v1.GetMetricsResponse
	41, // [41:49] is the sub-list for method output_type
	33, // [33:41] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_common_proto_init()
	file_cache_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
