// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: zones.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Zone types
type ZoneType int32

const (
	ZoneType_ZONE_TYPE_UNSPECIFIED ZoneType = 0
	ZoneType_ZONE_TYPE_PRIMARY     ZoneType = 1
	ZoneType_ZONE_TYPE_SECONDARY   ZoneType = 2
	ZoneType_ZONE_TYPE_STUB        ZoneType = 3
	ZoneType_ZONE_TYPE_FORWARD     ZoneType = 4
)

// Enum value maps for ZoneType.
var (
	ZoneType_name = map[int32]string{
		0: "ZONE_TYPE_UNSPECIFIED",
		1: "ZONE_TYPE_PRIMARY",
		2: "ZONE_TYPE_SECONDARY",
		3: "ZONE_TYPE_STUB",
		4: "ZONE_TYPE_FORWARD",
	}
	ZoneType_value = map[string]int32{
		"ZONE_TYPE_UNSPECIFIED": 0,
		"ZONE_TYPE_PRIMARY":     1,
		"ZONE_TYPE_SECONDARY":   2,
		"ZONE_TYPE_STUB":        3,
		"ZONE_TYPE_FORWARD":     4,
	}
)

func (x ZoneType) Enum() *ZoneType {
	p := new(ZoneType)
	*p = x
	return p
}

func (x ZoneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoneType) Descriptor() protoreflect.EnumDescriptor {
	return file_zones_proto_enumTypes[0].Descriptor()
}

func (ZoneType) Type() protoreflect.EnumType {
	return &file_zones_proto_enumTypes[0]
}

func (x ZoneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoneType.Descriptor instead.
func (ZoneType) EnumDescriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{0}
}

// Update operation types
type UpdateOperation int32

const (
	UpdateOperation_UPDATE_OPERATION_UNSPECIFIED UpdateOperation = 0
	UpdateOperation_UPDATE_OPERATION_ADD         UpdateOperation = 1
	UpdateOperation_UPDATE_OPERATION_DELETE      UpdateOperation = 2
	UpdateOperation_UPDATE_OPERATION_REPLACE     UpdateOperation = 3
)

// Enum value maps for UpdateOperation.
var (
	UpdateOperation_name = map[int32]string{
		0: "UPDATE_OPERATION_UNSPECIFIED",
		1: "UPDATE_OPERATION_ADD",
		2: "UPDATE_OPERATION_DELETE",
		3: "UPDATE_OPERATION_REPLACE",
	}
	UpdateOperation_value = map[string]int32{
		"UPDATE_OPERATION_UNSPECIFIED": 0,
		"UPDATE_OPERATION_ADD":         1,
		"UPDATE_OPERATION_DELETE":      2,
		"UPDATE_OPERATION_REPLACE":     3,
	}
)

func (x UpdateOperation) Enum() *UpdateOperation {
	p := new(UpdateOperation)
	*p = x
	return p
}

func (x UpdateOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_zones_proto_enumTypes[1].Descriptor()
}

func (UpdateOperation) Type() protoreflect.EnumType {
	return &file_zones_proto_enumTypes[1]
}

func (x UpdateOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateOperation.Descriptor instead.
func (UpdateOperation) EnumDescriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{1}
}

type ZoneEvent_EventType int32

const (
	ZoneEvent_EVENT_TYPE_UNSPECIFIED    ZoneEvent_EventType = 0
	ZoneEvent_EVENT_TYPE_ZONE_RELOADED  ZoneEvent_EventType = 1
	ZoneEvent_EVENT_TYPE_RECORD_ADDED   ZoneEvent_EventType = 2
	ZoneEvent_EVENT_TYPE_RECORD_UPDATED ZoneEvent_EventType = 3
	ZoneEvent_EVENT_TYPE_RECORD_DELETED ZoneEvent_EventType = 4
	ZoneEvent_EVENT_TYPE_SERIAL_CHANGED ZoneEvent_EventType = 5
	ZoneEvent_EVENT_TYPE_ZONE_ERROR     ZoneEvent_EventType = 6
)

// Enum value maps for ZoneEvent_EventType.
var (
	ZoneEvent_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_ZONE_RELOADED",
		2: "EVENT_TYPE_RECORD_ADDED",
		3: "EVENT_TYPE_RECORD_UPDATED",
		4: "EVENT_TYPE_RECORD_DELETED",
		5: "EVENT_TYPE_SERIAL_CHANGED",
		6: "EVENT_TYPE_ZONE_ERROR",
	}
	ZoneEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":    0,
		"EVENT_TYPE_ZONE_RELOADED":  1,
		"EVENT_TYPE_RECORD_ADDED":   2,
		"EVENT_TYPE_RECORD_UPDATED": 3,
		"EVENT_TYPE_RECORD_DELETED": 4,
		"EVENT_TYPE_SERIAL_CHANGED": 5,
		"EVENT_TYPE_ZONE_ERROR":     6,
	}
)

func (x ZoneEvent_EventType) Enum() *ZoneEvent_EventType {
	p := new(ZoneEvent_EventType)
	*p = x
	return p
}

func (x ZoneEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoneEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_zones_proto_enumTypes[2].Descriptor()
}

func (ZoneEvent_EventType) Type() protoreflect.EnumType {
	return &file_zones_proto_enumTypes[2]
}

func (x ZoneEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoneEvent_EventType.Descriptor instead.
func (ZoneEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{17, 0}
}

// Zone represents a DNS zone
type Zone struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type       ZoneType               `protobuf:"varint,2,opt,name=type,proto3,enum=dnsscience.v1.ZoneType" json:"type,omitempty"`
	File       string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	LastReload *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_reload,json=lastReload,proto3" json:"last_reload,omitempty"`
	Status     string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // loaded, error, pending
	Soa        *Zone_SOA              `protobuf:"bytes,6,opt,name=soa,proto3" json:"soa,omitempty"`
	// Zone statistics
	RecordCount     int32  `protobuf:"varint,7,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	DnssecEnabled   bool   `protobuf:"varint,8,opt,name=dnssec_enabled,json=dnssecEnabled,proto3" json:"dnssec_enabled,omitempty"`
	DnssecAlgorithm string `protobuf:"bytes,9,opt,name=dnssec_algorithm,json=dnssecAlgorithm,proto3" json:"dnssec_algorithm,omitempty"`
	// For secondary/stub zones
	Primaries    []string               `protobuf:"bytes,10,rep,name=primaries,proto3" json:"primaries,omitempty"`
	LastTransfer *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_transfer,json=lastTransfer,proto3" json:"last_transfer,omitempty"`
	// Transfer configuration
	NotifySlaves  []string `protobuf:"bytes,12,rep,name=notify_slaves,json=notifySlaves,proto3" json:"notify_slaves,omitempty"`
	AllowTransfer []string `protobuf:"bytes,13,rep,name=allow_transfer,json=allowTransfer,proto3" json:"allow_transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_zones_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{0}
}

func (x *Zone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Zone) GetType() ZoneType {
	if x != nil {
		return x.Type
	}
	return ZoneType_ZONE_TYPE_UNSPECIFIED
}

func (x *Zone) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Zone) GetLastReload() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReload
	}
	return nil
}

func (x *Zone) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Zone) GetSoa() *Zone_SOA {
	if x != nil {
		return x.Soa
	}
	return nil
}

func (x *Zone) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *Zone) GetDnssecEnabled() bool {
	if x != nil {
		return x.DnssecEnabled
	}
	return false
}

func (x *Zone) GetDnssecAlgorithm() string {
	if x != nil {
		return x.DnssecAlgorithm
	}
	return ""
}

func (x *Zone) GetPrimaries() []string {
	if x != nil {
		return x.Primaries
	}
	return nil
}

func (x *Zone) GetLastTransfer() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransfer
	}
	return nil
}

func (x *Zone) GetNotifySlaves() []string {
	if x != nil {
		return x.NotifySlaves
	}
	return nil
}

func (x *Zone) GetAllowTransfer() []string {
	if x != nil {
		return x.AllowTransfer
	}
	return nil
}

// ListZonesRequest
type ListZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ZoneType               `protobuf:"varint,1,opt,name=type,proto3,enum=dnsscience.v1.ZoneType" json:"type,omitempty"`     // Filter by type (optional, 0 = all)
	NamePattern   string                 `protobuf:"bytes,2,opt,name=name_pattern,json=namePattern,proto3" json:"name_pattern,omitempty"` // Wildcard pattern (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesRequest) Reset() {
	*x = ListZonesRequest{}
	mi := &file_zones_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesRequest) ProtoMessage() {}

func (x *ListZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesRequest.ProtoReflect.Descriptor instead.
func (*ListZonesRequest) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{1}
}

func (x *ListZonesRequest) GetType() ZoneType {
	if x != nil {
		return x.Type
	}
	return ZoneType_ZONE_TYPE_UNSPECIFIED
}

func (x *ListZonesRequest) GetNamePattern() string {
	if x != nil {
		return x.NamePattern
	}
	return ""
}

// ListZonesResponse
type ListZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []*Zone                `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListZonesResponse) Reset() {
	*x = ListZonesResponse{}
	mi := &file_zones_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListZonesResponse) ProtoMessage() {}

func (x *ListZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListZonesResponse.ProtoReflect.Descriptor instead.
func (*ListZonesResponse) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{2}
}

func (x *ListZonesResponse) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *ListZonesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// GetZoneRequest
type GetZoneRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZoneName       string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	IncludeRecords bool                   `protobuf:"varint,2,opt,name=include_records,json=includeRecords,proto3" json:"include_records,omitempty"` // Include all records
	RecordType     string                 `protobuf:"bytes,3,opt,name=record_type,json=recordType,proto3" json:"record_type,omitempty"`              // Filter records by type (optional)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetZoneRequest) Reset() {
	*x = GetZoneRequest{}
	mi := &file_zones_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneRequest) ProtoMessage() {}

func (x *GetZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneRequest.ProtoReflect.Descriptor instead.
func (*GetZoneRequest) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{3}
}

func (x *GetZoneRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *GetZoneRequest) GetIncludeRecords() bool {
	if x != nil {
		return x.IncludeRecords
	}
	return false
}

func (x *GetZoneRequest) GetRecordType() string {
	if x != nil {
		return x.RecordType
	}
	return ""
}

// GetZoneResponse
type GetZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          *Zone                  `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	Records       []*ResourceRecord      `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"` // If include_records=true
	Meta          *ResponseMeta          `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetZoneResponse) Reset() {
	*x = GetZoneResponse{}
	mi := &file_zones_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetZoneResponse) ProtoMessage() {}

func (x *GetZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetZoneResponse.ProtoReflect.Descriptor instead.
func (*GetZoneResponse) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{4}
}

func (x *GetZoneResponse) GetZone() *Zone {
	if x != nil {
		return x.Zone
	}
	return nil
}

func (x *GetZoneResponse) GetRecords() []*ResourceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetZoneResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// ReloadZoneRequest
type ReloadZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneName      string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	VerifyOnly    bool                   `protobuf:"varint,2,opt,name=verify_only,json=verifyOnly,proto3" json:"verify_only,omitempty"` // Verify but don't load
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadZoneRequest) Reset() {
	*x = ReloadZoneRequest{}
	mi := &file_zones_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadZoneRequest) ProtoMessage() {}

func (x *ReloadZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadZoneRequest.ProtoReflect.Descriptor instead.
func (*ReloadZoneRequest) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadZoneRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *ReloadZoneRequest) GetVerifyOnly() bool {
	if x != nil {
		return x.VerifyOnly
	}
	return false
}

// ReloadZoneResponse
type ReloadZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneName      string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	OldSerial     uint32                 `protobuf:"varint,4,opt,name=old_serial,json=oldSerial,proto3" json:"old_serial,omitempty"`
	NewSerial     uint32                 `protobuf:"varint,5,opt,name=new_serial,json=newSerial,proto3" json:"new_serial,omitempty"`
	RecordCount   int32                  `protobuf:"varint,6,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Errors        []string               `protobuf:"bytes,8,rep,name=errors,proto3" json:"errors,omitempty"` // Parse errors if any
	Meta          *ResponseMeta          `protobuf:"bytes,9,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadZoneResponse) Reset() {
	*x = ReloadZoneResponse{}
	mi := &file_zones_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadZoneResponse) ProtoMessage() {}

func (x *ReloadZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadZoneResponse.ProtoReflect.Descriptor instead.
func (*ReloadZoneResponse) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{6}
}

func (x *ReloadZoneResponse) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *ReloadZoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadZoneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReloadZoneResponse) GetOldSerial() uint32 {
	if x != nil {
		return x.OldSerial
	}
	return 0
}

func (x *ReloadZoneResponse) GetNewSerial() uint32 {
	if x != nil {
		return x.NewSerial
	}
	return 0
}

func (x *ReloadZoneResponse) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *ReloadZoneResponse) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ReloadZoneResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ReloadZoneResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// NotifyRequest for NOTIFY operation
type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneName      string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Servers       []string               `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"` // Specific servers (optional, all if empty)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_zones_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *NotifyRequest) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

// NotifyResponse
type NotifyResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ZoneName      string                         `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Serial        uint32                         `protobuf:"varint,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Results       []*NotifyResponse_NotifyResult `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Meta          *ResponseMeta                  `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_zones_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyResponse) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *NotifyResponse) GetSerial() uint32 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *NotifyResponse) GetResults() []*NotifyResponse_NotifyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *NotifyResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// TransferZoneRequest
type TransferZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneName      string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	TransferType  string                 `protobuf:"bytes,2,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"` // axfr or ixfr
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`                                 // Specific primary (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferZoneRequest) Reset() {
	*x = TransferZoneRequest{}
	mi := &file_zones_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferZoneRequest) ProtoMessage() {}

func (x *TransferZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferZoneRequest.ProtoReflect.Descriptor instead.
func (*TransferZoneRequest) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{9}
}

func (x *TransferZoneRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *TransferZoneRequest) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *TransferZoneRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

// TransferZoneResponse
type TransferZoneResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZoneName       string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	TransferType   string                 `protobuf:"bytes,2,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	OldSerial      uint32                 `protobuf:"varint,4,opt,name=old_serial,json=oldSerial,proto3" json:"old_serial,omitempty"`
	NewSerial      uint32                 `protobuf:"varint,5,opt,name=new_serial,json=newSerial,proto3" json:"new_serial,omitempty"`
	RecordsChanged int32                  `protobuf:"varint,6,opt,name=records_changed,json=recordsChanged,proto3" json:"records_changed,omitempty"`
	Duration       *durationpb.Duration   `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Meta           *ResponseMeta          `protobuf:"bytes,9,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferZoneResponse) Reset() {
	*x = TransferZoneResponse{}
	mi := &file_zones_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferZoneResponse) ProtoMessage() {}

func (x *TransferZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferZoneResponse.ProtoReflect.Descriptor instead.
func (*TransferZoneResponse) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{10}
}

func (x *TransferZoneResponse) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *TransferZoneResponse) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *TransferZoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferZoneResponse) GetOldSerial() uint32 {
	if x != nil {
		return x.OldSerial
	}
	return 0
}

func (x *TransferZoneResponse) GetNewSerial() uint32 {
	if x != nil {
		return x.NewSerial
	}
	return 0
}

func (x *TransferZoneResponse) GetRecordsChanged() int32 {
	if x != nil {
		return x.RecordsChanged
	}
	return 0
}

func (x *TransferZoneResponse) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *TransferZoneResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TransferZoneResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// RecordUpdate for dynamic DNS
type RecordUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     UpdateOperation        `protobuf:"varint,1,opt,name=operation,proto3,enum=dnsscience.v1.UpdateOperation" json:"operation,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Ttl           uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                      // For add/replace operations
	OldData       string                 `protobuf:"bytes,6,opt,name=old_data,json=oldData,proto3" json:"old_data,omitempty"` // For replace operations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordUpdate) Reset() {
	*x = RecordUpdate{}
	mi := &file_zones_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUpdate) ProtoMessage() {}

func (x *RecordUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUpdate.ProtoReflect.Descriptor instead.
func (*RecordUpdate) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{11}
}

func (x *RecordUpdate) GetOperation() UpdateOperation {
	if x != nil {
		return x.Operation
	}
	return UpdateOperation_UPDATE_OPERATION_UNSPECIFIED
}

func (x *RecordUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecordUpdate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecordUpdate) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *RecordUpdate) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RecordUpdate) GetOldData() string {
	if x != nil {
		return x.OldData
	}
	return ""
}

// UpdateRecordsRequest
type UpdateRecordsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ZoneName        string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Updates         []*RecordUpdate        `protobuf:"bytes,2,rep,name=updates,proto3" json:"updates,omitempty"`
	IncrementSerial bool                   `protobuf:"varint,3,opt,name=increment_serial,json=incrementSerial,proto3" json:"increment_serial,omitempty"` // Auto-increment zone serial
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRecordsRequest) Reset() {
	*x = UpdateRecordsRequest{}
	mi := &file_zones_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordsRequest) ProtoMessage() {}

func (x *UpdateRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordsRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordsRequest) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRecordsRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *UpdateRecordsRequest) GetUpdates() []*RecordUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *UpdateRecordsRequest) GetIncrementSerial() bool {
	if x != nil {
		return x.IncrementSerial
	}
	return false
}

// UpdateRecordsResponse
type UpdateRecordsResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	ZoneName      string                                `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Results       []*UpdateRecordsResponse_UpdateResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	NewSerial     uint32                                `protobuf:"varint,3,opt,name=new_serial,json=newSerial,proto3" json:"new_serial,omitempty"`
	Applied       int32                                 `protobuf:"varint,4,opt,name=applied,proto3" json:"applied,omitempty"`
	Failed        int32                                 `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	Meta          *ResponseMeta                         `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordsResponse) Reset() {
	*x = UpdateRecordsResponse{}
	mi := &file_zones_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordsResponse) ProtoMessage() {}

func (x *UpdateRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordsResponse.ProtoReflect.Descriptor instead.
func (*UpdateRecordsResponse) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRecordsResponse) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *UpdateRecordsResponse) GetResults() []*UpdateRecordsResponse_UpdateResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *UpdateRecordsResponse) GetNewSerial() uint32 {
	if x != nil {
		return x.NewSerial
	}
	return 0
}

func (x *UpdateRecordsResponse) GetApplied() int32 {
	if x != nil {
		return x.Applied
	}
	return 0
}

func (x *UpdateRecordsResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *UpdateRecordsResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// GetRecordsRequest
type GetRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneName      string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // Optional: specific name
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // Optional: specific type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsRequest) Reset() {
	*x = GetRecordsRequest{}
	mi := &file_zones_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsRequest) ProtoMessage() {}

func (x *GetRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetRecordsRequest) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{14}
}

func (x *GetRecordsRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *GetRecordsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetRecordsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// GetRecordsResponse
type GetRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneName      string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Records       []*ResourceRecord      `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordsResponse) Reset() {
	*x = GetRecordsResponse{}
	mi := &file_zones_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordsResponse) ProtoMessage() {}

func (x *GetRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordsResponse.ProtoReflect.Descriptor instead.
func (*GetRecordsResponse) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{15}
}

func (x *GetRecordsResponse) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *GetRecordsResponse) GetRecords() []*ResourceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetRecordsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetRecordsResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// WatchZoneRequest
type WatchZoneRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZoneName       string                 `protobuf:"bytes,1,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	IncludeUpdates bool                   `protobuf:"varint,2,opt,name=include_updates,json=includeUpdates,proto3" json:"include_updates,omitempty"` // Include record update events
	IncludeReloads bool                   `protobuf:"varint,3,opt,name=include_reloads,json=includeReloads,proto3" json:"include_reloads,omitempty"` // Include zone reload events
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchZoneRequest) Reset() {
	*x = WatchZoneRequest{}
	mi := &file_zones_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchZoneRequest) ProtoMessage() {}

func (x *WatchZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchZoneRequest.ProtoReflect.Descriptor instead.
func (*WatchZoneRequest) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{16}
}

func (x *WatchZoneRequest) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *WatchZoneRequest) GetIncludeUpdates() bool {
	if x != nil {
		return x.IncludeUpdates
	}
	return false
}

func (x *WatchZoneRequest) GetIncludeReloads() bool {
	if x != nil {
		return x.IncludeReloads
	}
	return false
}

// ZoneEvent represents a zone change event
type ZoneEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      ZoneEvent_EventType    `protobuf:"varint,1,opt,name=type,proto3,enum=dnsscience.v1.ZoneEvent_EventType" json:"type,omitempty"`
	ZoneName  string                 `protobuf:"bytes,2,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Event details
	//
	// Types that are valid to be assigned to Detail:
	//
	//	*ZoneEvent_Record
	//	*ZoneEvent_NewSerial
	//	*ZoneEvent_ErrorMessage
	Detail        isZoneEvent_Detail `protobuf_oneof:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoneEvent) Reset() {
	*x = ZoneEvent{}
	mi := &file_zones_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneEvent) ProtoMessage() {}

func (x *ZoneEvent) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneEvent.ProtoReflect.Descriptor instead.
func (*ZoneEvent) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{17}
}

func (x *ZoneEvent) GetType() ZoneEvent_EventType {
	if x != nil {
		return x.Type
	}
	return ZoneEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *ZoneEvent) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *ZoneEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ZoneEvent) GetDetail() isZoneEvent_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *ZoneEvent) GetRecord() *RecordUpdate {
	if x != nil {
		if x, ok := x.Detail.(*ZoneEvent_Record); ok {
			return x.Record
		}
	}
	return nil
}

func (x *ZoneEvent) GetNewSerial() uint32 {
	if x != nil {
		if x, ok := x.Detail.(*ZoneEvent_NewSerial); ok {
			return x.NewSerial
		}
	}
	return 0
}

func (x *ZoneEvent) GetErrorMessage() string {
	if x != nil {
		if x, ok := x.Detail.(*ZoneEvent_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return ""
}

type isZoneEvent_Detail interface {
	isZoneEvent_Detail()
}

type ZoneEvent_Record struct {
	Record *RecordUpdate `protobuf:"bytes,4,opt,name=record,proto3,oneof"`
}

type ZoneEvent_NewSerial struct {
	NewSerial uint32 `protobuf:"varint,5,opt,name=new_serial,json=newSerial,proto3,oneof"`
}

type ZoneEvent_ErrorMessage struct {
	ErrorMessage string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*ZoneEvent_Record) isZoneEvent_Detail() {}

func (*ZoneEvent_NewSerial) isZoneEvent_Detail() {}

func (*ZoneEvent_ErrorMessage) isZoneEvent_Detail() {}

// SOA info
type Zone_SOA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Primary       string                 `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Admin         string                 `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	Serial        uint32                 `protobuf:"varint,3,opt,name=serial,proto3" json:"serial,omitempty"`
	Refresh       uint32                 `protobuf:"varint,4,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Retry         uint32                 `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	Expire        uint32                 `protobuf:"varint,6,opt,name=expire,proto3" json:"expire,omitempty"`
	Minimum       uint32                 `protobuf:"varint,7,opt,name=minimum,proto3" json:"minimum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone_SOA) Reset() {
	*x = Zone_SOA{}
	mi := &file_zones_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone_SOA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone_SOA) ProtoMessage() {}

func (x *Zone_SOA) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone_SOA.ProtoReflect.Descriptor instead.
func (*Zone_SOA) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Zone_SOA) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *Zone_SOA) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

func (x *Zone_SOA) GetSerial() uint32 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *Zone_SOA) GetRefresh() uint32 {
	if x != nil {
		return x.Refresh
	}
	return 0
}

func (x *Zone_SOA) GetRetry() uint32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *Zone_SOA) GetExpire() uint32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *Zone_SOA) GetMinimum() uint32 {
	if x != nil {
		return x.Minimum
	}
	return 0
}

type NotifyResponse_NotifyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Acknowledged  bool                   `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse_NotifyResult) Reset() {
	*x = NotifyResponse_NotifyResult{}
	mi := &file_zones_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse_NotifyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse_NotifyResult) ProtoMessage() {}

func (x *NotifyResponse_NotifyResult) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse_NotifyResult.ProtoReflect.Descriptor instead.
func (*NotifyResponse_NotifyResult) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{8, 0}
}

func (x *NotifyResponse_NotifyResult) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *NotifyResponse_NotifyResult) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *NotifyResponse_NotifyResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateRecordsResponse_UpdateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *RecordUpdate          `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordsResponse_UpdateResult) Reset() {
	*x = UpdateRecordsResponse_UpdateResult{}
	mi := &file_zones_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordsResponse_UpdateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordsResponse_UpdateResult) ProtoMessage() {}

func (x *UpdateRecordsResponse_UpdateResult) ProtoReflect() protoreflect.Message {
	mi := &file_zones_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordsResponse_UpdateResult.ProtoReflect.Descriptor instead.
func (*UpdateRecordsResponse_UpdateResult) Descriptor() ([]byte, []int) {
	return file_zones_proto_rawDescGZIP(), []int{13, 0}
}

func (x *UpdateRecordsResponse_UpdateResult) GetUpdate() *RecordUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *UpdateRecordsResponse_UpdateResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRecordsResponse_UpdateResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_zones_proto protoreflect.FileDescriptor

const file_zones_proto_rawDesc = "" +
	"\n" +
	"\vzones.proto\x12\rdnsscience.v1\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xad\x05\n" +
	"\x04Zone\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.dnsscience.v1.ZoneTypeR\x04type\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x12;\n" +
	"\vlast_reload\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastReload\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12)\n" +
	"\x03soa\x18\x06 \x01(\v2\x17.dnsscience.v1.Zone.SOAR\x03soa\x12!\n" +
	"\frecord_count\x18\a \x01(\x05R\vrecordCount\x12%\n" +
	"\x0ednssec_enabled\x18\b \x01(\bR\rdnssecEnabled\x12)\n" +
	"\x10dnssec_algorithm\x18\t \x01(\tR\x0fdnssecAlgorithm\x12\x1c\n" +
	"\tprimaries\x18\n" +
	" \x03(\tR\tprimaries\x12?\n" +
	"\rlast_transfer\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\flastTransfer\x12#\n" +
	"\rnotify_slaves\x18\f \x03(\tR\fnotifySlaves\x12%\n" +
	"\x0eallow_transfer\x18\r \x03(\tR\rallowTransfer\x1a\xaf\x01\n" +
	"\x03SOA\x12\x18\n" +
	"\aprimary\x18\x01 \x01(\tR\aprimary\x12\x14\n" +
	"\x05admin\x18\x02 \x01(\tR\x05admin\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\rR\x06serial\x12\x18\n" +
	"\arefresh\x18\x04 \x01(\rR\arefresh\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\rR\x05retry\x12\x16\n" +
	"\x06expire\x18\x06 \x01(\rR\x06expire\x12\x18\n" +
	"\aminimum\x18\a \x01(\rR\aminimum\"b\n" +
	"\x10ListZonesRequest\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.dnsscience.v1.ZoneTypeR\x04type\x12!\n" +
	"\fname_pattern\x18\x02 \x01(\tR\vnamePattern\"T\n" +
	"\x11ListZonesResponse\x12)\n" +
	"\x05zones\x18\x01 \x03(\v2\x13.dnsscience.v1.ZoneR\x05zones\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"w\n" +
	"\x0eGetZoneRequest\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12'\n" +
	"\x0finclude_records\x18\x02 \x01(\bR\x0eincludeRecords\x12\x1f\n" +
	"\vrecord_type\x18\x03 \x01(\tR\n" +
	"recordType\"\xa4\x01\n" +
	"\x0fGetZoneResponse\x12'\n" +
	"\x04zone\x18\x01 \x01(\v2\x13.dnsscience.v1.ZoneR\x04zone\x127\n" +
	"\arecords\x18\x02 \x03(\v2\x1d.dnsscience.v1.ResourceRecordR\arecords\x12/\n" +
	"\x04meta\x18\x03 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"Q\n" +
	"\x11ReloadZoneRequest\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12\x1f\n" +
	"\vverify_only\x18\x02 \x01(\bR\n" +
	"verifyOnly\"\xc6\x02\n" +
	"\x12ReloadZoneResponse\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"old_serial\x18\x04 \x01(\rR\toldSerial\x12\x1d\n" +
	"\n" +
	"new_serial\x18\x05 \x01(\rR\tnewSerial\x12!\n" +
	"\frecord_count\x18\x06 \x01(\x05R\vrecordCount\x125\n" +
	"\bduration\x18\a \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x16\n" +
	"\x06errors\x18\b \x03(\tR\x06errors\x12/\n" +
	"\x04meta\x18\t \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"F\n" +
	"\rNotifyRequest\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12\x18\n" +
	"\aservers\x18\x02 \x03(\tR\aservers\"\xa2\x02\n" +
	"\x0eNotifyResponse\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\rR\x06serial\x12D\n" +
	"\aresults\x18\x03 \x03(\v2*.dnsscience.v1.NotifyResponse.NotifyResultR\aresults\x12/\n" +
	"\x04meta\x18\x04 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\x1ad\n" +
	"\fNotifyResult\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\"\n" +
	"\facknowledged\x18\x02 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"o\n" +
	"\x13TransferZoneRequest\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12#\n" +
	"\rtransfer_type\x18\x02 \x01(\tR\ftransferType\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\"\xe6\x02\n" +
	"\x14TransferZoneResponse\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12#\n" +
	"\rtransfer_type\x18\x02 \x01(\tR\ftransferType\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"old_serial\x18\x04 \x01(\rR\toldSerial\x12\x1d\n" +
	"\n" +
	"new_serial\x18\x05 \x01(\rR\tnewSerial\x12'\n" +
	"\x0frecords_changed\x18\x06 \x01(\x05R\x0erecordsChanged\x125\n" +
	"\bduration\x18\a \x01(\v2\x19.google.protobuf.DurationR\bduration\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12/\n" +
	"\x04meta\x18\t \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"\xb5\x01\n" +
	"\fRecordUpdate\x12<\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1e.dnsscience.v1.UpdateOperationR\toperation\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12\x19\n" +
	"\bold_data\x18\x06 \x01(\tR\aoldData\"\x95\x01\n" +
	"\x14UpdateRecordsRequest\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x125\n" +
	"\aupdates\x18\x02 \x03(\v2\x1b.dnsscience.v1.RecordUpdateR\aupdates\x12)\n" +
	"\x10increment_serial\x18\x03 \x01(\bR\x0fincrementSerial\"\xf8\x02\n" +
	"\x15UpdateRecordsResponse\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12K\n" +
	"\aresults\x18\x02 \x03(\v21.dnsscience.v1.UpdateRecordsResponse.UpdateResultR\aresults\x12\x1d\n" +
	"\n" +
	"new_serial\x18\x03 \x01(\rR\tnewSerial\x12\x18\n" +
	"\aapplied\x18\x04 \x01(\x05R\aapplied\x12\x16\n" +
	"\x06failed\x18\x05 \x01(\x05R\x06failed\x12/\n" +
	"\x04meta\x18\x06 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\x1as\n" +
	"\fUpdateResult\x123\n" +
	"\x06update\x18\x01 \x01(\v2\x1b.dnsscience.v1.RecordUpdateR\x06update\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"X\n" +
	"\x11GetRecordsRequest\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xb1\x01\n" +
	"\x12GetRecordsResponse\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x127\n" +
	"\arecords\x18\x02 \x03(\v2\x1d.dnsscience.v1.ResourceRecordR\arecords\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12/\n" +
	"\x04meta\x18\x04 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"\x81\x01\n" +
	"\x10WatchZoneRequest\x12\x1b\n" +
	"\tzone_name\x18\x01 \x01(\tR\bzoneName\x12'\n" +
	"\x0finclude_updates\x18\x02 \x01(\bR\x0eincludeUpdates\x12'\n" +
	"\x0finclude_reloads\x18\x03 \x01(\bR\x0eincludeReloads\"\x80\x04\n" +
	"\tZoneEvent\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".dnsscience.v1.ZoneEvent.EventTypeR\x04type\x12\x1b\n" +
	"\tzone_name\x18\x02 \x01(\tR\bzoneName\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\x06record\x18\x04 \x01(\v2\x1b.dnsscience.v1.RecordUpdateH\x00R\x06record\x12\x1f\n" +
	"\n" +
	"new_serial\x18\x05 \x01(\rH\x00R\tnewSerial\x12%\n" +
	"\rerror_message\x18\x06 \x01(\tH\x00R\ferrorMessage\"\xda\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EVENT_TYPE_ZONE_RELOADED\x10\x01\x12\x1b\n" +
	"\x17EVENT_TYPE_RECORD_ADDED\x10\x02\x12\x1d\n" +
	"\x19EVENT_TYPE_RECORD_UPDATED\x10\x03\x12\x1d\n" +
	"\x19EVENT_TYPE_RECORD_DELETED\x10\x04\x12\x1d\n" +
	"\x19EVENT_TYPE_SERIAL_CHANGED\x10\x05\x12\x19\n" +
	"\x15EVENT_TYPE_ZONE_ERROR\x10\x06B\b\n" +
	"\x06detail*\x80\x01\n" +
	"\bZoneType\x12\x19\n" +
	"\x15ZONE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ZONE_TYPE_PRIMARY\x10\x01\x12\x17\n" +
	"\x13ZONE_TYPE_SECONDARY\x10\x02\x12\x12\n" +
	"\x0eZONE_TYPE_STUB\x10\x03\x12\x15\n" +
	"\x11ZONE_TYPE_FORWARD\x10\x04*\x88\x01\n" +
	"\x0fUpdateOperation\x12 \n" +
	"\x1cUPDATE_OPERATION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14UPDATE_OPERATION_ADD\x10\x01\x12\x1b\n" +
	"\x17UPDATE_OPERATION_DELETE\x10\x02\x12\x1c\n" +
	"\x18UPDATE_OPERATION_REPLACE\x10\x032\x9e\x05\n" +
	"\vZoneService\x12N\n" +
	"\tListZones\x12\x1f.dnsscience.v1.ListZonesRequest\x1a .dnsscience.v1.ListZonesResponse\x12H\n" +
	"\aGetZone\x12\x1d.dnsscience.v1.GetZoneRequest\x1a\x1e.dnsscience.v1.GetZoneResponse\x12Q\n" +
	"\n" +
	"ReloadZone\x12 .dnsscience.v1.ReloadZoneRequest\x1a!.dnsscience.v1.ReloadZoneResponse\x12P\n" +
	"\x11NotifySecondaries\x12\x1c.dnsscience.v1.NotifyRequest\x1a\x1d.dnsscience.v1.NotifyResponse\x12W\n" +
	"\fTransferZone\x12\".dnsscience.v1.TransferZoneRequest\x1a#.dnsscience.v1.TransferZoneResponse\x12Z\n" +
	"\rUpdateRecords\x12#.dnsscience.v1.UpdateRecordsRequest\x1a$.dnsscience.v1.UpdateRecordsResponse\x12Q\n" +
	"\n" +
	"GetRecords\x12 .dnsscience.v1.GetRecordsRequest\x1a!.dnsscience.v1.GetRecordsResponse\x12H\n" +
	"\tWatchZone\x12\x1f.dnsscience.v1.WatchZoneRequest\x1a\x18.dnsscience.v1.ZoneEvent0\x01B5Z3github.com/dnsscience/dnsscienced/api/grpc/proto/pbb\x06proto3"

var (
	file_zones_proto_rawDescOnce sync.Once
	file_zones_proto_rawDescData []byte
)

func file_zones_proto_rawDescGZIP() []byte {
	file_zones_proto_rawDescOnce.Do(func() {
		file_zones_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zones_proto_rawDesc), len(file_zones_proto_rawDesc)))
	})
	return file_zones_proto_rawDescData
}

var file_zones_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_zones_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_zones_proto_goTypes = []any{
	(ZoneType)(0),                              // 0: dnsscience.v1.ZoneType
	(UpdateOperation)(0),                       // 1: dnsscience.v1.UpdateOperation
	(ZoneEvent_EventType)(0),                   // 2: dnsscience.v1.ZoneEvent.EventType
	(*Zone)(nil),                               // 3: dnsscience.v1.Zone
	(*ListZonesRequest)(nil),                   // 4: dnsscience.v1.ListZonesRequest
	(*ListZonesResponse)(nil),                  // 5: dnsscience.v1.ListZonesResponse
	(*GetZoneRequest)(nil),                     // 6: dnsscience.v1.GetZoneRequest
	(*GetZoneResponse)(nil),                    // 7: dnsscience.v1.GetZoneResponse
	(*ReloadZoneRequest)(nil),                  // 8: dnsscience.v1.ReloadZoneRequest
	(*ReloadZoneResponse)(nil),                 // 9: dnsscience.v1.ReloadZoneResponse
	(*NotifyRequest)(nil),                      // 10: dnsscience.v1.NotifyRequest
	(*NotifyResponse)(nil),                     // 11: dnsscience.v1.NotifyResponse
	(*TransferZoneRequest)(nil),                // 12: dnsscience.v1.TransferZoneRequest
	(*TransferZoneResponse)(nil),               // 13: dnsscience.v1.TransferZoneResponse
	(*RecordUpdate)(nil),                       // 14: dnsscience.v1.RecordUpdate
	(*UpdateRecordsRequest)(nil),               // 15: dnsscience.v1.UpdateRecordsRequest
	(*UpdateRecordsResponse)(nil),              // 16: dnsscience.v1.UpdateRecordsResponse
	(*GetRecordsRequest)(nil),                  // 17: dnsscience.v1.GetRecordsRequest
	(*GetRecordsResponse)(nil),                 // 18: dnsscience.v1.GetRecordsResponse
	(*WatchZoneRequest)(nil),                   // 19: dnsscience.v1.WatchZoneRequest
	(*ZoneEvent)(nil),                          // 20: dnsscience.v1.ZoneEvent
	(*Zone_SOA)(nil),                           // 21: dnsscience.v1.Zone.SOA
	(*NotifyResponse_NotifyResult)(nil),        // 22: dnsscience.v1.NotifyResponse.NotifyResult
	(*UpdateRecordsResponse_UpdateResult)(nil), // 23: dnsscience.v1.UpdateRecordsResponse.UpdateResult
	(*timestamppb.Timestamp)(nil),              // 24: google.protobuf.Timestamp
	(*ResourceRecord)(nil),                     // 25: dnsscience.v1.ResourceRecord
	(*ResponseMeta)(nil),                       // 26: dnsscience.v1.ResponseMeta
	(*durationpb.Duration)(nil),                // 27: google.protobuf.Duration
}
var file_zones_proto_depIdxs = []int32{
	0,  // 0: dnsscience.v1.Zone.type:type_name -> dnsscience.v1.ZoneType
	24, // 1: dnsscience.v1.Zone.last_reload:type_name -> google.protobuf.Timestamp
	21, // 2: dnsscience.v1.Zone.soa:type_name -> dnsscience.v1.Zone.SOA
	24, // 3: dnsscience.v1.Zone.last_transfer:type_name -> google.protobuf.Timestamp
	0,  // 4: dnsscience.v1.ListZonesRequest.type:type_name -> dnsscience.v1.ZoneType
	3,  // 5: dnsscience.v1.ListZonesResponse.zones:type_name -> dnsscience.v1.Zone
	3,  // 6: dnsscience.v1.GetZoneResponse.zone:type_name -> dnsscience.v1.Zone
	25, // 7: dnsscience.v1.GetZoneResponse.records:type_name -> dnsscience.v1.ResourceRecord
	26, // 8: dnsscience.v1.GetZoneResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	27, // 9: dnsscience.v1.ReloadZoneResponse.duration:type_name -> google.protobuf.Duration
	26, // 10: dnsscience.v1.ReloadZoneResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	22, // 11: dnsscience.v1.NotifyResponse.results:type_name -> dnsscience.v1.NotifyResponse.NotifyResult
	26, // 12: dnsscience.v1.NotifyResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	27, // 13: dnsscience.v1.TransferZoneResponse.duration:type_name -> google.protobuf.Duration
	26, // 14: dnsscience.v1.TransferZoneResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	1,  // 15: dnsscience.v1.RecordUpdate.operation:type_name -> dnsscience.v1.UpdateOperation
	14, // 16: dnsscience.v1.UpdateRecordsRequest.updates:type_name -> dnsscience.v1.RecordUpdate
	23, // 17: dnsscience.v1.UpdateRecordsResponse.results:type_name -> dnsscience.v1.UpdateRecordsResponse.UpdateResult
	26, // 18: dnsscience.v1.UpdateRecordsResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	25, // 19: dnsscience.v1.GetRecordsResponse.records:type_name -> dnsscience.v1.ResourceRecord
	26, // 20: dnsscience.v1.GetRecordsResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	2,  // 21: dnsscience.v1.ZoneEvent.type:type_name -> dnsscience.v1.ZoneEvent.EventType
	24, // 22: dnsscience.v1.ZoneEvent.timestamp:type_name -> google.protobuf.Timestamp
	14, // 23: dnsscience.v1.ZoneEvent.record:type_name -> dnsscience.v1.RecordUpdate
	14, // 24: dnsscience.v1.UpdateRecordsResponse.UpdateResult.update:type_name -> dnsscience.v1.RecordUpdate
	4,  // 25: dnsscience.v1.ZoneService.ListZones:input_type -> dnsscience.v1.ListZonesRequest
	6,  // 26: dnsscience.v1.ZoneService.GetZone:input_type -> dnsscience.v1.GetZoneRequest
	8,  // 27: dnsscience.v1.ZoneService.ReloadZone:input_type -> dnsscience.v1.ReloadZoneRequest
	10, // 28: dnsscience.v1.ZoneService.NotifySecondaries:input_type -> dnsscience.v1.NotifyRequest
	12, // 29: dnsscience.v1.ZoneService.TransferZone:input_type -> dnsscience.v1.TransferZoneRequest
	15, // 30: dnsscience.v1.ZoneService.UpdateRecords:input_type -> dnsscience.v1.UpdateRecordsRequest
	17, // 31: dnsscience.v1.ZoneService.GetRecords:input_type -> dnsscience.v1.GetRecordsRequest
	19, // 32: dnsscience.v1.ZoneService.WatchZone:input_type -> dnsscience.v1.WatchZoneRequest
	5,  // 33: dnsscience.v1.ZoneService.ListZones:output_type -> dnsscience.v1.ListZonesResponse
	7,  // 34: dnsscience.v1.ZoneService.GetZone:output_type -> dnsscience.v1.GetZoneResponse
	9,  // 35: dnsscience.v1.ZoneService.ReloadZone:output_type -> dnsscience.v1.ReloadZoneResponse
	11, // 36: dnsscience.v1.ZoneService.NotifySecondaries:output_type -> dnsscience.v1.NotifyResponse
	13, // 37: dnsscience.v1.ZoneService.TransferZone:output_type -> dnsscience.v1.TransferZoneResponse
	16, // 38: dnsscience.v1.ZoneService.UpdateRecords:output_type -> dnsscience.v1.UpdateRecordsResponse
	18, // 39: dnsscience.v1.ZoneService.GetRecords:output_type -> dnsscience.v1.GetRecordsResponse
	20, // 40: dnsscience.v1.ZoneService.WatchZone:output_type -> dnsscience.v1.ZoneEvent
	33, // [33:41] is the sub-list for method output_type
	25, // [25:33] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_zones_proto_init() }
func file_zones_proto_init() {
	if File_zones_proto != nil {
		return
	}
	file_common_proto_init()
	file_zones_proto_msgTypes[17].OneofWrappers = []any{
		(*ZoneEvent_Record)(nil),
		(*ZoneEvent_NewSerial)(nil),
		(*ZoneEvent_ErrorMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zones_proto_rawDesc), len(file_zones_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zones_proto_goTypes,
		DependencyIndexes: file_zones_proto_depIdxs,
		EnumInfos:         file_zones_proto_enumTypes,
		MessageInfos:      file_zones_proto_msgTypes,
	}.Build()
	File_zones_proto = out.File
	file_zones_proto_goTypes = nil
	file_zones_proto_depIdxs = nil
}
