// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: cache.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlushCacheRequest_FlushScope int32

const (
	FlushCacheRequest_FLUSH_SCOPE_UNSPECIFIED FlushCacheRequest_FlushScope = 0
	FlushCacheRequest_FLUSH_SCOPE_ALL         FlushCacheRequest_FlushScope = 1
	FlushCacheRequest_FLUSH_SCOPE_DOMAIN      FlushCacheRequest_FlushScope = 2
	FlushCacheRequest_FLUSH_SCOPE_TYPE        FlushCacheRequest_FlushScope = 3
	FlushCacheRequest_FLUSH_SCOPE_EXACT       FlushCacheRequest_FlushScope = 4
)

// Enum value maps for FlushCacheRequest_FlushScope.
var (
	FlushCacheRequest_FlushScope_name = map[int32]string{
		0: "FLUSH_SCOPE_UNSPECIFIED",
		1: "FLUSH_SCOPE_ALL",
		2: "FLUSH_SCOPE_DOMAIN",
		3: "FLUSH_SCOPE_TYPE",
		4: "FLUSH_SCOPE_EXACT",
	}
	FlushCacheRequest_FlushScope_value = map[string]int32{
		"FLUSH_SCOPE_UNSPECIFIED": 0,
		"FLUSH_SCOPE_ALL":         1,
		"FLUSH_SCOPE_DOMAIN":      2,
		"FLUSH_SCOPE_TYPE":        3,
		"FLUSH_SCOPE_EXACT":       4,
	}
)

func (x FlushCacheRequest_FlushScope) Enum() *FlushCacheRequest_FlushScope {
	p := new(FlushCacheRequest_FlushScope)
	*p = x
	return p
}

func (x FlushCacheRequest_FlushScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlushCacheRequest_FlushScope) Descriptor() protoreflect.EnumDescriptor {
	return file_cache_proto_enumTypes[0].Descriptor()
}

func (FlushCacheRequest_FlushScope) Type() protoreflect.EnumType {
	return &file_cache_proto_enumTypes[0]
}

func (x FlushCacheRequest_FlushScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlushCacheRequest_FlushScope.Descriptor instead.
func (FlushCacheRequest_FlushScope) EnumDescriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{5, 0}
}

type CacheEvent_EventType int32

const (
	CacheEvent_EVENT_TYPE_UNSPECIFIED       CacheEvent_EventType = 0
	CacheEvent_EVENT_TYPE_HIT               CacheEvent_EventType = 1
	CacheEvent_EVENT_TYPE_MISS              CacheEvent_EventType = 2
	CacheEvent_EVENT_TYPE_EVICT             CacheEvent_EventType = 3
	CacheEvent_EVENT_TYPE_STORE             CacheEvent_EventType = 4
	CacheEvent_EVENT_TYPE_DELETE            CacheEvent_EventType = 5
	CacheEvent_EVENT_TYPE_PREFETCH          CacheEvent_EventType = 6
	CacheEvent_EVENT_TYPE_PREFETCH_COMPLETE CacheEvent_EventType = 7
)

// Enum value maps for CacheEvent_EventType.
var (
	CacheEvent_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_HIT",
		2: "EVENT_TYPE_MISS",
		3: "EVENT_TYPE_EVICT",
		4: "EVENT_TYPE_STORE",
		5: "EVENT_TYPE_DELETE",
		6: "EVENT_TYPE_PREFETCH",
		7: "EVENT_TYPE_PREFETCH_COMPLETE",
	}
	CacheEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":       0,
		"EVENT_TYPE_HIT":               1,
		"EVENT_TYPE_MISS":              2,
		"EVENT_TYPE_EVICT":             3,
		"EVENT_TYPE_STORE":             4,
		"EVENT_TYPE_DELETE":            5,
		"EVENT_TYPE_PREFETCH":          6,
		"EVENT_TYPE_PREFETCH_COMPLETE": 7,
	}
)

func (x CacheEvent_EventType) Enum() *CacheEvent_EventType {
	p := new(CacheEvent_EventType)
	*p = x
	return p
}

func (x CacheEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_cache_proto_enumTypes[1].Descriptor()
}

func (CacheEvent_EventType) Type() protoreflect.EnumType {
	return &file_cache_proto_enumTypes[1]
}

func (x CacheEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheEvent_EventType.Descriptor instead.
func (CacheEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{10, 0}
}

// GetCacheStatsRequest
type GetCacheStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backend       string                 `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"` // memory, redis, etc. (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheStatsRequest) Reset() {
	*x = GetCacheStatsRequest{}
	mi := &file_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheStatsRequest) ProtoMessage() {}

func (x *GetCacheStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheStatsRequest.ProtoReflect.Descriptor instead.
func (*GetCacheStatsRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GetCacheStatsRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

// Cache statistics
type CacheStats struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Entries     int64                  `protobuf:"varint,1,opt,name=entries,proto3" json:"entries,omitempty"`
	SizeBytes   int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MaxBytes    int64                  `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	Utilization float32                `protobuf:"fixed32,4,opt,name=utilization,proto3" json:"utilization,omitempty"`
	// Performance metrics
	Hits    int64   `protobuf:"varint,5,opt,name=hits,proto3" json:"hits,omitempty"`
	Misses  int64   `protobuf:"varint,6,opt,name=misses,proto3" json:"misses,omitempty"`
	HitRate float32 `protobuf:"fixed32,7,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"`
	// Entry breakdown by type
	ByType map[string]int64 `protobuf:"bytes,8,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// TTL statistics
	AvgTtlSeconds uint32 `protobuf:"varint,9,opt,name=avg_ttl_seconds,json=avgTtlSeconds,proto3" json:"avg_ttl_seconds,omitempty"`
	MinTtlSeconds uint32 `protobuf:"varint,10,opt,name=min_ttl_seconds,json=minTtlSeconds,proto3" json:"min_ttl_seconds,omitempty"`
	MaxTtlSeconds uint32 `protobuf:"varint,11,opt,name=max_ttl_seconds,json=maxTtlSeconds,proto3" json:"max_ttl_seconds,omitempty"`
	// Eviction metrics
	EvictionsTotal    int64            `protobuf:"varint,12,opt,name=evictions_total,json=evictionsTotal,proto3" json:"evictions_total,omitempty"`
	EvictionsByReason map[string]int64 `protobuf:"bytes,13,rep,name=evictions_by_reason,json=evictionsByReason,proto3" json:"evictions_by_reason,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Time window
	MeasuredAt    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"`
	Backend       string                 `protobuf:"bytes,15,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheStats) Reset() {
	*x = CacheStats{}
	mi := &file_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheStats) ProtoMessage() {}

func (x *CacheStats) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheStats.ProtoReflect.Descriptor instead.
func (*CacheStats) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CacheStats) GetEntries() int64 {
	if x != nil {
		return x.Entries
	}
	return 0
}

func (x *CacheStats) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CacheStats) GetMaxBytes() int64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *CacheStats) GetUtilization() float32 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *CacheStats) GetHits() int64 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *CacheStats) GetMisses() int64 {
	if x != nil {
		return x.Misses
	}
	return 0
}

func (x *CacheStats) GetHitRate() float32 {
	if x != nil {
		return x.HitRate
	}
	return 0
}

func (x *CacheStats) GetByType() map[string]int64 {
	if x != nil {
		return x.ByType
	}
	return nil
}

func (x *CacheStats) GetAvgTtlSeconds() uint32 {
	if x != nil {
		return x.AvgTtlSeconds
	}
	return 0
}

func (x *CacheStats) GetMinTtlSeconds() uint32 {
	if x != nil {
		return x.MinTtlSeconds
	}
	return 0
}

func (x *CacheStats) GetMaxTtlSeconds() uint32 {
	if x != nil {
		return x.MaxTtlSeconds
	}
	return 0
}

func (x *CacheStats) GetEvictionsTotal() int64 {
	if x != nil {
		return x.EvictionsTotal
	}
	return 0
}

func (x *CacheStats) GetEvictionsByReason() map[string]int64 {
	if x != nil {
		return x.EvictionsByReason
	}
	return nil
}

func (x *CacheStats) GetMeasuredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MeasuredAt
	}
	return nil
}

func (x *CacheStats) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

// GetCacheStatsResponse
type GetCacheStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *CacheStats            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheStatsResponse) Reset() {
	*x = GetCacheStatsResponse{}
	mi := &file_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheStatsResponse) ProtoMessage() {}

func (x *GetCacheStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheStatsResponse.ProtoReflect.Descriptor instead.
func (*GetCacheStatsResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{2}
}

func (x *GetCacheStatsResponse) GetStats() *CacheStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetCacheStatsResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// CacheLookupRequest
type CacheLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // Optional: filter by type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheLookupRequest) Reset() {
	*x = CacheLookupRequest{}
	mi := &file_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheLookupRequest) ProtoMessage() {}

func (x *CacheLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheLookupRequest.ProtoReflect.Descriptor instead.
func (*CacheLookupRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{3}
}

func (x *CacheLookupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CacheLookupRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// CacheLookupResponse
type CacheLookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CacheEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheLookupResponse) Reset() {
	*x = CacheLookupResponse{}
	mi := &file_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheLookupResponse) ProtoMessage() {}

func (x *CacheLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheLookupResponse.ProtoReflect.Descriptor instead.
func (*CacheLookupResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{4}
}

func (x *CacheLookupResponse) GetEntries() []*CacheEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *CacheLookupResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CacheLookupResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// FlushCacheRequest
type FlushCacheRequest struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Scope             FlushCacheRequest_FlushScope `protobuf:"varint,1,opt,name=scope,proto3,enum=dnsscience.v1.FlushCacheRequest_FlushScope" json:"scope,omitempty"`
	Domain            string                       `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`                                                 // For FLUSH_SCOPE_DOMAIN
	Type              string                       `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                                     // For FLUSH_SCOPE_TYPE
	IncludeSubdomains bool                         `protobuf:"varint,4,opt,name=include_subdomains,json=includeSubdomains,proto3" json:"include_subdomains,omitempty"` // For FLUSH_SCOPE_DOMAIN
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FlushCacheRequest) Reset() {
	*x = FlushCacheRequest{}
	mi := &file_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushCacheRequest) ProtoMessage() {}

func (x *FlushCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushCacheRequest.ProtoReflect.Descriptor instead.
func (*FlushCacheRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{5}
}

func (x *FlushCacheRequest) GetScope() FlushCacheRequest_FlushScope {
	if x != nil {
		return x.Scope
	}
	return FlushCacheRequest_FLUSH_SCOPE_UNSPECIFIED
}

func (x *FlushCacheRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *FlushCacheRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FlushCacheRequest) GetIncludeSubdomains() bool {
	if x != nil {
		return x.IncludeSubdomains
	}
	return false
}

// FlushCacheResponse
type FlushCacheResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntriesRemoved int32                  `protobuf:"varint,1,opt,name=entries_removed,json=entriesRemoved,proto3" json:"entries_removed,omitempty"`
	BytesFreed     int64                  `protobuf:"varint,2,opt,name=bytes_freed,json=bytesFreed,proto3" json:"bytes_freed,omitempty"`
	FlushedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=flushed_at,json=flushedAt,proto3" json:"flushed_at,omitempty"`
	Meta           *ResponseMeta          `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlushCacheResponse) Reset() {
	*x = FlushCacheResponse{}
	mi := &file_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushCacheResponse) ProtoMessage() {}

func (x *FlushCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushCacheResponse.ProtoReflect.Descriptor instead.
func (*FlushCacheResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{6}
}

func (x *FlushCacheResponse) GetEntriesRemoved() int32 {
	if x != nil {
		return x.EntriesRemoved
	}
	return 0
}

func (x *FlushCacheResponse) GetBytesFreed() int64 {
	if x != nil {
		return x.BytesFreed
	}
	return 0
}

func (x *FlushCacheResponse) GetFlushedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FlushedAt
	}
	return nil
}

func (x *FlushCacheResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// PrefetchRequest
type PrefetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Types         []string               `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`        // Types to prefetch for each name
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"` // 0=low, 1=normal, 2=high
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefetchRequest) Reset() {
	*x = PrefetchRequest{}
	mi := &file_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchRequest) ProtoMessage() {}

func (x *PrefetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefetchRequest.ProtoReflect.Descriptor instead.
func (*PrefetchRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{7}
}

func (x *PrefetchRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *PrefetchRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *PrefetchRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// PrefetchResponse
type PrefetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queued        int32                  `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Meta          *ResponseMeta          `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefetchResponse) Reset() {
	*x = PrefetchResponse{}
	mi := &file_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchResponse) ProtoMessage() {}

func (x *PrefetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefetchResponse.ProtoReflect.Descriptor instead.
func (*PrefetchResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{8}
}

func (x *PrefetchResponse) GetQueued() int32 {
	if x != nil {
		return x.Queued
	}
	return 0
}

func (x *PrefetchResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *PrefetchResponse) GetMeta() *ResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// WatchCacheRequest for cache event streaming
type WatchCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []string               `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`                                      // Event types to watch: hit, miss, evict, prefetch
	DomainPattern string                 `protobuf:"bytes,2,opt,name=domain_pattern,json=domainPattern,proto3" json:"domain_pattern,omitempty"` // Optional: filter by domain pattern
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCacheRequest) Reset() {
	*x = WatchCacheRequest{}
	mi := &file_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCacheRequest) ProtoMessage() {}

func (x *WatchCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCacheRequest.ProtoReflect.Descriptor instead.
func (*WatchCacheRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{9}
}

func (x *WatchCacheRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *WatchCacheRequest) GetDomainPattern() string {
	if x != nil {
		return x.DomainPattern
	}
	return ""
}

// CacheEvent represents a cache operation
type CacheEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      CacheEvent_EventType   `protobuf:"varint,1,opt,name=type,proto3,enum=dnsscience.v1.CacheEvent_EventType" json:"type,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Query info
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	QueryType string `protobuf:"bytes,4,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	// For HIT/MISS events
	Reason string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"` // For MISS: expired, never_cached, etc.
	// For EVICT events
	EvictionReason string `protobuf:"bytes,6,opt,name=eviction_reason,json=evictionReason,proto3" json:"eviction_reason,omitempty"` // lru, expired, other
	// For STORE/DELETE events
	Entry         *CacheEntry `protobuf:"bytes,7,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheEvent) Reset() {
	*x = CacheEvent{}
	mi := &file_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEvent) ProtoMessage() {}

func (x *CacheEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEvent.ProtoReflect.Descriptor instead.
func (*CacheEvent) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{10}
}

func (x *CacheEvent) GetType() CacheEvent_EventType {
	if x != nil {
		return x.Type
	}
	return CacheEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *CacheEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CacheEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CacheEvent) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *CacheEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CacheEvent) GetEvictionReason() string {
	if x != nil {
		return x.EvictionReason
	}
	return ""
}

func (x *CacheEvent) GetEntry() *CacheEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_cache_proto protoreflect.FileDescriptor

const file_cache_proto_rawDesc = "" +
	"\n" +
	"\vcache.proto\x12\rdnsscience.v1\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x14GetCacheStatsRequest\x12\x18\n" +
	"\abackend\x18\x01 \x01(\tR\abackend\"\xe6\x05\n" +
	"\n" +
	"CacheStats\x12\x18\n" +
	"\aentries\x18\x01 \x01(\x03R\aentries\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tmax_bytes\x18\x03 \x01(\x03R\bmaxBytes\x12 \n" +
	"\vutilization\x18\x04 \x01(\x02R\vutilization\x12\x12\n" +
	"\x04hits\x18\x05 \x01(\x03R\x04hits\x12\x16\n" +
	"\x06misses\x18\x06 \x01(\x03R\x06misses\x12\x19\n" +
	"\bhit_rate\x18\a \x01(\x02R\ahitRate\x12>\n" +
	"\aby_type\x18\b \x03(\v2%.dnsscience.v1.CacheStats.ByTypeEntryR\x06byType\x12&\n" +
	"\x0favg_ttl_seconds\x18\t \x01(\rR\ravgTtlSeconds\x12&\n" +
	"\x0fmin_ttl_seconds\x18\n" +
	" \x01(\rR\rminTtlSeconds\x12&\n" +
	"\x0fmax_ttl_seconds\x18\v \x01(\rR\rmaxTtlSeconds\x12'\n" +
	"\x0fevictions_total\x18\f \x01(\x03R\x0eevictionsTotal\x12`\n" +
	"\x13evictions_by_reason\x18\r \x03(\v20.dnsscience.v1.CacheStats.EvictionsByReasonEntryR\x11evictionsByReason\x12;\n" +
	"\vmeasured_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"measuredAt\x12\x18\n" +
	"\abackend\x18\x0f \x01(\tR\abackend\x1a9\n" +
	"\vByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aD\n" +
	"\x16EvictionsByReasonEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"y\n" +
	"\x15GetCacheStatsResponse\x12/\n" +
	"\x05stats\x18\x01 \x01(\v2\x19.dnsscience.v1.CacheStatsR\x05stats\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"<\n" +
	"\x12CacheLookupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x91\x01\n" +
	"\x13CacheLookupResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.dnsscience.v1.CacheEntryR\aentries\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12/\n" +
	"\x04meta\x18\x03 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"\xb7\x02\n" +
	"\x11FlushCacheRequest\x12A\n" +
	"\x05scope\x18\x01 \x01(\x0e2+.dnsscience.v1.FlushCacheRequest.FlushScopeR\x05scope\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12-\n" +
	"\x12include_subdomains\x18\x04 \x01(\bR\x11includeSubdomains\"\x83\x01\n" +
	"\n" +
	"FlushScope\x12\x1b\n" +
	"\x17FLUSH_SCOPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFLUSH_SCOPE_ALL\x10\x01\x12\x16\n" +
	"\x12FLUSH_SCOPE_DOMAIN\x10\x02\x12\x14\n" +
	"\x10FLUSH_SCOPE_TYPE\x10\x03\x12\x15\n" +
	"\x11FLUSH_SCOPE_EXACT\x10\x04\"\xca\x01\n" +
	"\x12FlushCacheResponse\x12'\n" +
	"\x0fentries_removed\x18\x01 \x01(\x05R\x0eentriesRemoved\x12\x1f\n" +
	"\vbytes_freed\x18\x02 \x01(\x03R\n" +
	"bytesFreed\x129\n" +
	"\n" +
	"flushed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tflushedAt\x12/\n" +
	"\x04meta\x18\x04 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"Y\n" +
	"\x0fPrefetchRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x12\x14\n" +
	"\x05types\x18\x02 \x03(\tR\x05types\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"s\n" +
	"\x10PrefetchResponse\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\x05R\x06queued\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\x12/\n" +
	"\x04meta\x18\x03 \x01(\v2\x1b.dnsscience.v1.ResponseMetaR\x04meta\"P\n" +
	"\x11WatchCacheRequest\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x12%\n" +
	"\x0edomain_pattern\x18\x02 \x01(\tR\rdomainPattern\"\xf5\x03\n" +
	"\n" +
	"CacheEvent\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.dnsscience.v1.CacheEvent.EventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"query_type\x18\x04 \x01(\tR\tqueryType\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12'\n" +
	"\x0feviction_reason\x18\x06 \x01(\tR\x0eevictionReason\x12/\n" +
	"\x05entry\x18\a \x01(\v2\x19.dnsscience.v1.CacheEntryR\x05entry\"\xce\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_TYPE_HIT\x10\x01\x12\x13\n" +
	"\x0fEVENT_TYPE_MISS\x10\x02\x12\x14\n" +
	"\x10EVENT_TYPE_EVICT\x10\x03\x12\x14\n" +
	"\x10EVENT_TYPE_STORE\x10\x04\x12\x15\n" +
	"\x11EVENT_TYPE_DELETE\x10\x05\x12\x17\n" +
	"\x13EVENT_TYPE_PREFETCH\x10\x06\x12 \n" +
	"\x1cEVENT_TYPE_PREFETCH_COMPLETE\x10\a2\x9e\x03\n" +
	"\fCacheService\x12U\n" +
	"\bGetStats\x12#.dnsscience.v1.GetCacheStatsRequest\x1a$.dnsscience.v1.GetCacheStatsResponse\x12O\n" +
	"\x06Lookup\x12!.dnsscience.v1.CacheLookupRequest\x1a\".dnsscience.v1.CacheLookupResponse\x12L\n" +
	"\x05Flush\x12 .dnsscience.v1.FlushCacheRequest\x1a!.dnsscience.v1.FlushCacheResponse\x12K\n" +
	"\bPrefetch\x12\x1e.dnsscience.v1.PrefetchRequest\x1a\x1f.dnsscience.v1.PrefetchResponse\x12K\n" +
	"\n" +
	"WatchCache\x12 .dnsscience.v1.WatchCacheRequest\x1a\x19.dnsscience.v1.CacheEvent0\x01B5Z3github.com/dnsscience/dnsscienced/api/grpc/proto/pbb\x06proto3"

var (
	file_cache_proto_rawDescOnce sync.Once
	file_cache_proto_rawDescData []byte
)

func file_cache_proto_rawDescGZIP() []byte {
	file_cache_proto_rawDescOnce.Do(func() {
		file_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)))
	})
	return file_cache_proto_rawDescData
}

var file_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_cache_proto_goTypes = []any{
	(FlushCacheRequest_FlushScope)(0), // 0: dnsscience.v1.FlushCacheRequest.FlushScope
	(CacheEvent_EventType)(0),         // 1: dnsscience.v1.CacheEvent.EventType
	(*GetCacheStatsRequest)(nil),      // 2: dnsscience.v1.GetCacheStatsRequest
	(*CacheStats)(nil),                // 3: dnsscience.v1.CacheStats
	(*GetCacheStatsResponse)(nil),     // 4: dnsscience.v1.GetCacheStatsResponse
	(*CacheLookupRequest)(nil),        // 5: dnsscience.v1.CacheLookupRequest
	(*CacheLookupResponse)(nil),       // 6: dnsscience.v1.CacheLookupResponse
	(*FlushCacheRequest)(nil),         // 7: dnsscience.v1.FlushCacheRequest
	(*FlushCacheResponse)(nil),        // 8: dnsscience.v1.FlushCacheResponse
	(*PrefetchRequest)(nil),           // 9: dnsscience.v1.PrefetchRequest
	(*PrefetchResponse)(nil),          // 10: dnsscience.v1.PrefetchResponse
	(*WatchCacheRequest)(nil),         // 11: dnsscience.v1.WatchCacheRequest
	(*CacheEvent)(nil),                // 12: dnsscience.v1.CacheEvent
	nil,                               // 13: dnsscience.v1.CacheStats.ByTypeEntry
	nil,                               // 14: dnsscience.v1.CacheStats.EvictionsByReasonEntry
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
	(*ResponseMeta)(nil),              // 16: dnsscience.v1.ResponseMeta
	(*CacheEntry)(nil),                // 17: dnsscience.v1.CacheEntry
}
var file_cache_proto_depIdxs = []int32{
	13, // 0: dnsscience.v1.CacheStats.by_type:type_name -> dnsscience.v1.CacheStats.ByTypeEntry
	14, // 1: dnsscience.v1.CacheStats.evictions_by_reason:type_name -> dnsscience.v1.CacheStats.EvictionsByReasonEntry
	15, // 2: dnsscience.v1.CacheStats.measured_at:type_name -> google.protobuf.Timestamp
	3,  // 3: dnsscience.v1.GetCacheStatsResponse.stats:type_name -> dnsscience.v1.CacheStats
	16, // 4: dnsscience.v1.GetCacheStatsResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	17, // 5: dnsscience.v1.CacheLookupResponse.entries:type_name -> dnsscience.v1.CacheEntry
	16, // 6: dnsscience.v1.CacheLookupResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	0,  // 7: dnsscience.v1.FlushCacheRequest.scope:type_name -> dnsscience.v1.FlushCacheRequest.FlushScope
	15, // 8: dnsscience.v1.FlushCacheResponse.flushed_at:type_name -> google.protobuf.Timestamp
	16, // 9: dnsscience.v1.FlushCacheResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	16, // 10: dnsscience.v1.PrefetchResponse.meta:type_name -> dnsscience.v1.ResponseMeta
	1,  // 11: dnsscience.v1.CacheEvent.type:type_name -> dnsscience.v1.CacheEvent.EventType
	15, // 12: dnsscience.v1.CacheEvent.timestamp:type_name -> google.protobuf.Timestamp
	17, // 13: dnsscience.v1.CacheEvent.entry:type_name -> dnsscience.v1.CacheEntry
	2,  // 14: dnsscience.v1.CacheService.GetStats:input_type -> dnsscience.v1.GetCacheStatsRequest
	5,  // 15: dnsscience.v1.CacheService.Lookup:input_type -> dnsscience.v1.CacheLookupRequest
	7,  // 16: dnsscience.v1.CacheService.Flush:input_type -> dnsscience.v1.FlushCacheRequest
	9,  // 17: dnsscience.v1.CacheService.Prefetch:input_type -> dnsscience.v1.PrefetchRequest
	11, // 18: dnsscience.v1.CacheService.WatchCache:input_type -> dnsscience.v1.WatchCacheRequest
	4,  // 19: dnsscience.v1.CacheService.GetStats:output_type -> dnsscience.v1.GetCacheStatsResponse
	6,  // 20: dnsscience.v1.CacheService.Lookup:output_type -> dnsscience.v1.CacheLookupResponse
	8,  // 21: dnsscience.v1.CacheService.Flush:output_type -> dnsscience.v1.FlushCacheResponse
	10, // 22: dnsscience.v1.CacheService.Prefetch:output_type -> dnsscience.v1.PrefetchResponse
	12, // 23: dnsscience.v1.CacheService.WatchCache:output_type -> dnsscience.v1.CacheEvent
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cache_proto_init() }
func file_cache_proto_init() {
	if File_cache_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_proto_goTypes,
		DependencyIndexes: file_cache_proto_depIdxs,
		EnumInfos:         file_cache_proto_enumTypes,
		MessageInfos:      file_cache_proto_msgTypes,
	}.Build()
	File_cache_proto = out.File
	file_cache_proto_goTypes = nil
	file_cache_proto_depIdxs = nil
}
