// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryMeta contains metadata about a DNS query/response
type QueryMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIp      string                 `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientPort    int32                  `protobuf:"varint,2,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // udp, tcp, dot, doh, doq
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	RespondedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=responded_at,json=respondedAt,proto3" json:"responded_at,omitempty"`
	Latency       *durationpb.Duration   `protobuf:"bytes,6,opt,name=latency,proto3" json:"latency,omitempty"`
	ServerId      string                 `protobuf:"bytes,7,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // correlation ID
	Cached        bool                   `protobuf:"varint,9,opt,name=cached,proto3" json:"cached,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // custom tags from plugins
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMeta) Reset() {
	*x = QueryMeta{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMeta) ProtoMessage() {}

func (x *QueryMeta) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMeta.ProtoReflect.Descriptor instead.
func (*QueryMeta) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *QueryMeta) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *QueryMeta) GetClientPort() int32 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *QueryMeta) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *QueryMeta) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *QueryMeta) GetRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RespondedAt
	}
	return nil
}

func (x *QueryMeta) GetLatency() *durationpb.Duration {
	if x != nil {
		return x.Latency
	}
	return nil
}

func (x *QueryMeta) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *QueryMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryMeta) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *QueryMeta) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ResourceRecord represents a DNS resource record
type ResourceRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`   // A, AAAA, MX, CNAME, etc.
	Class string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"` // IN (default)
	Ttl   uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Data  string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`   // string representation of record data
	Rdata []byte                 `protobuf:"bytes,6,opt,name=rdata,proto3" json:"rdata,omitempty"` // DNS wire format record data
	// DNSSEC validation status
	DnssecStatus  string `protobuf:"bytes,7,opt,name=dnssec_status,json=dnssecStatus,proto3" json:"dnssec_status,omitempty"` // insecure, secure, bogus, indeterminate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRecord) Reset() {
	*x = ResourceRecord{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRecord) ProtoMessage() {}

func (x *ResourceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRecord.ProtoReflect.Descriptor instead.
func (*ResourceRecord) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceRecord) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ResourceRecord) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *ResourceRecord) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ResourceRecord) GetRdata() []byte {
	if x != nil {
		return x.Rdata
	}
	return nil
}

func (x *ResourceRecord) GetDnssecStatus() string {
	if x != nil {
		return x.DnssecStatus
	}
	return ""
}

// DNSSECValidation contains DNSSEC validation details
type DNSSECValidation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Validated        bool                   `protobuf:"varint,1,opt,name=validated,proto3" json:"validated,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                              // secure, insecure, bogus, indeterminate
	ChainStatus      string                 `protobuf:"bytes,3,opt,name=chain_status,json=chainStatus,proto3" json:"chain_status,omitempty"` // chain validated or reason for failure
	ValidationErrors []string               `protobuf:"bytes,4,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	Details          map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DNSSECValidation) Reset() {
	*x = DNSSECValidation{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSSECValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSSECValidation) ProtoMessage() {}

func (x *DNSSECValidation) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSSECValidation.ProtoReflect.Descriptor instead.
func (*DNSSECValidation) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *DNSSECValidation) GetValidated() bool {
	if x != nil {
		return x.Validated
	}
	return false
}

func (x *DNSSECValidation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DNSSECValidation) GetChainStatus() string {
	if x != nil {
		return x.ChainStatus
	}
	return ""
}

func (x *DNSSECValidation) GetValidationErrors() []string {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

func (x *DNSSECValidation) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// CacheEntry represents a cached DNS record
type CacheEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Class         string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	Ttl           uint32                 `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	OriginalTtl   uint32                 `protobuf:"varint,5,opt,name=original_ttl,json=originalTtl,proto3" json:"original_ttl,omitempty"`
	Data          []string               `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty"` // multiple records
	CachedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"` // where it came from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheEntry) Reset() {
	*x = CacheEntry{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEntry) ProtoMessage() {}

func (x *CacheEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEntry.ProtoReflect.Descriptor instead.
func (*CacheEntry) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *CacheEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CacheEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CacheEntry) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *CacheEntry) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *CacheEntry) GetOriginalTtl() uint32 {
	if x != nil {
		return x.OriginalTtl
	}
	return 0
}

func (x *CacheEntry) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CacheEntry) GetCachedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CachedAt
	}
	return nil
}

func (x *CacheEntry) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CacheEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// Error response format
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Standard response wrapper (for consistency)
type ResponseMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMeta) Reset() {
	*x = ResponseMeta{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMeta) ProtoMessage() {}

func (x *ResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMeta.ProtoReflect.Descriptor instead.
func (*ResponseMeta) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResponseMeta) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ResponseMeta) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// DNSName for type-safe domain name handling
type DNSName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // FQDN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSName) Reset() {
	*x = DNSName{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSName) ProtoMessage() {}

func (x *DNSName) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSName.ProtoReflect.Descriptor instead.
func (*DNSName) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *DNSName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DNSType for type-safe record type handling
type DNSType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // A, AAAA, MX, CNAME, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSType) Reset() {
	*x = DNSType{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSType) ProtoMessage() {}

func (x *DNSType) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSType.ProtoReflect.Descriptor instead.
func (*DNSType) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *DNSType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// DNSClass for type-safe class handling
type DNSClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"` // IN (default), CH, HS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSClass) Reset() {
	*x = DNSClass{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSClass) ProtoMessage() {}

func (x *DNSClass) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSClass.ProtoReflect.Descriptor instead.
func (*DNSClass) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *DNSClass) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\rdnsscience.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xdb\x03\n" +
	"\tQueryMeta\x12\x1b\n" +
	"\tclient_ip\x18\x01 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vclient_port\x18\x02 \x01(\x05R\n" +
	"clientPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12;\n" +
	"\vreceived_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12=\n" +
	"\fresponded_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vrespondedAt\x123\n" +
	"\alatency\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\alatency\x12\x1b\n" +
	"\tserver_id\x18\a \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\x12\x16\n" +
	"\x06cached\x18\t \x01(\bR\x06cached\x126\n" +
	"\x04tags\x18\n" +
	" \x03(\v2\".dnsscience.v1.QueryMeta.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x0eResourceRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12\x14\n" +
	"\x05rdata\x18\x06 \x01(\fR\x05rdata\x12#\n" +
	"\rdnssec_status\x18\a \x01(\tR\fdnssecStatus\"\x9c\x02\n" +
	"\x10DNSSECValidation\x12\x1c\n" +
	"\tvalidated\x18\x01 \x01(\bR\tvalidated\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fchain_status\x18\x03 \x01(\tR\vchainStatus\x12+\n" +
	"\x11validation_errors\x18\x04 \x03(\tR\x10validationErrors\x12F\n" +
	"\adetails\x18\x05 \x03(\v2,.dnsscience.v1.DNSSECValidation.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x02\n" +
	"\n" +
	"CacheEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\rR\x03ttl\x12!\n" +
	"\foriginal_ttl\x18\x05 \x01(\rR\voriginalTtl\x12\x12\n" +
	"\x04data\x18\x06 \x03(\tR\x04data\x127\n" +
	"\tcached_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bcachedAt\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\"\xbe\x01\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.dnsscience.v1.ErrorDetail.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x01\n" +
	"\fResponseMeta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12B\n" +
	"\aheaders\x18\x03 \x03(\v2(.dnsscience.v1.ResponseMeta.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1d\n" +
	"\aDNSName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1d\n" +
	"\aDNSType\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\" \n" +
	"\bDNSClass\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05classB5Z3github.com/dnsscience/dnsscienced/api/grpc/proto/pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_common_proto_goTypes = []any{
	(*QueryMeta)(nil),             // 0: dnsscience.v1.QueryMeta
	(*ResourceRecord)(nil),        // 1: dnsscience.v1.ResourceRecord
	(*DNSSECValidation)(nil),      // 2: dnsscience.v1.DNSSECValidation
	(*CacheEntry)(nil),            // 3: dnsscience.v1.CacheEntry
	(*ErrorDetail)(nil),           // 4: dnsscience.v1.ErrorDetail
	(*ResponseMeta)(nil),          // 5: dnsscience.v1.ResponseMeta
	(*DNSName)(nil),               // 6: dnsscience.v1.DNSName
	(*DNSType)(nil),               // 7: dnsscience.v1.DNSType
	(*DNSClass)(nil),              // 8: dnsscience.v1.DNSClass
	nil,                           // 9: dnsscience.v1.QueryMeta.TagsEntry
	nil,                           // 10: dnsscience.v1.DNSSECValidation.DetailsEntry
	nil,                           // 11: dnsscience.v1.ErrorDetail.MetadataEntry
	nil,                           // 12: dnsscience.v1.ResponseMeta.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 14: google.protobuf.Duration
}
var file_common_proto_depIdxs = []int32{
	13, // 0: dnsscience.v1.QueryMeta.received_at:type_name -> google.protobuf.Timestamp
	13, // 1: dnsscience.v1.QueryMeta.responded_at:type_name -> google.protobuf.Timestamp
	14, // 2: dnsscience.v1.QueryMeta.latency:type_name -> google.protobuf.Duration
	9,  // 3: dnsscience.v1.QueryMeta.tags:type_name -> dnsscience.v1.QueryMeta.TagsEntry
	10, // 4: dnsscience.v1.DNSSECValidation.details:type_name -> dnsscience.v1.DNSSECValidation.DetailsEntry
	13, // 5: dnsscience.v1.CacheEntry.cached_at:type_name -> google.protobuf.Timestamp
	13, // 6: dnsscience.v1.CacheEntry.expires_at:type_name -> google.protobuf.Timestamp
	11, // 7: dnsscience.v1.ErrorDetail.metadata:type_name -> dnsscience.v1.ErrorDetail.MetadataEntry
	13, // 8: dnsscience.v1.ResponseMeta.timestamp:type_name -> google.protobuf.Timestamp
	12, // 9: dnsscience.v1.ResponseMeta.headers:type_name -> dnsscience.v1.ResponseMeta.HeadersEntry
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
