// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: zones.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZoneService_ListZones_FullMethodName         = "/dnsscience.v1.ZoneService/ListZones"
	ZoneService_GetZone_FullMethodName           = "/dnsscience.v1.ZoneService/GetZone"
	ZoneService_ReloadZone_FullMethodName        = "/dnsscience.v1.ZoneService/ReloadZone"
	ZoneService_NotifySecondaries_FullMethodName = "/dnsscience.v1.ZoneService/NotifySecondaries"
	ZoneService_TransferZone_FullMethodName      = "/dnsscience.v1.ZoneService/TransferZone"
	ZoneService_UpdateRecords_FullMethodName     = "/dnsscience.v1.ZoneService/UpdateRecords"
	ZoneService_GetRecords_FullMethodName        = "/dnsscience.v1.ZoneService/GetRecords"
	ZoneService_WatchZone_FullMethodName         = "/dnsscience.v1.ZoneService/WatchZone"
)

// ZoneServiceClient is the client API for ZoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ZoneService manages DNS zones
type ZoneServiceClient interface {
	// ListZones returns all configured zones
	ListZones(ctx context.Context, in *ListZonesRequest, opts ...grpc.CallOption) (*ListZonesResponse, error)
	// GetZone returns details about a specific zone
	GetZone(ctx context.Context, in *GetZoneRequest, opts ...grpc.CallOption) (*GetZoneResponse, error)
	// ReloadZone reloads a zone from file
	ReloadZone(ctx context.Context, in *ReloadZoneRequest, opts ...grpc.CallOption) (*ReloadZoneResponse, error)
	// NotifySecondaries sends NOTIFY to secondary servers
	NotifySecondaries(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	// TransferZone initiates a zone transfer (for secondary zones)
	TransferZone(ctx context.Context, in *TransferZoneRequest, opts ...grpc.CallOption) (*TransferZoneResponse, error)
	// UpdateRecords adds/updates/deletes records (dynamic DNS)
	UpdateRecords(ctx context.Context, in *UpdateRecordsRequest, opts ...grpc.CallOption) (*UpdateRecordsResponse, error)
	// GetRecords retrieves records from a zone
	GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (*GetRecordsResponse, error)
	// WatchZone streams zone change events
	WatchZone(ctx context.Context, in *WatchZoneRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ZoneEvent], error)
}

type zoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneServiceClient(cc grpc.ClientConnInterface) ZoneServiceClient {
	return &zoneServiceClient{cc}
}

func (c *zoneServiceClient) ListZones(ctx context.Context, in *ListZonesRequest, opts ...grpc.CallOption) (*ListZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListZonesResponse)
	err := c.cc.Invoke(ctx, ZoneService_ListZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) GetZone(ctx context.Context, in *GetZoneRequest, opts ...grpc.CallOption) (*GetZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetZoneResponse)
	err := c.cc.Invoke(ctx, ZoneService_GetZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) ReloadZone(ctx context.Context, in *ReloadZoneRequest, opts ...grpc.CallOption) (*ReloadZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadZoneResponse)
	err := c.cc.Invoke(ctx, ZoneService_ReloadZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) NotifySecondaries(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, ZoneService_NotifySecondaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) TransferZone(ctx context.Context, in *TransferZoneRequest, opts ...grpc.CallOption) (*TransferZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferZoneResponse)
	err := c.cc.Invoke(ctx, ZoneService_TransferZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) UpdateRecords(ctx context.Context, in *UpdateRecordsRequest, opts ...grpc.CallOption) (*UpdateRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRecordsResponse)
	err := c.cc.Invoke(ctx, ZoneService_UpdateRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (*GetRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecordsResponse)
	err := c.cc.Invoke(ctx, ZoneService_GetRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zoneServiceClient) WatchZone(ctx context.Context, in *WatchZoneRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ZoneEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZoneService_ServiceDesc.Streams[0], ZoneService_WatchZone_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchZoneRequest, ZoneEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZoneService_WatchZoneClient = grpc.ServerStreamingClient[ZoneEvent]

// ZoneServiceServer is the server API for ZoneService service.
// All implementations must embed UnimplementedZoneServiceServer
// for forward compatibility.
//
// ZoneService manages DNS zones
type ZoneServiceServer interface {
	// ListZones returns all configured zones
	ListZones(context.Context, *ListZonesRequest) (*ListZonesResponse, error)
	// GetZone returns details about a specific zone
	GetZone(context.Context, *GetZoneRequest) (*GetZoneResponse, error)
	// ReloadZone reloads a zone from file
	ReloadZone(context.Context, *ReloadZoneRequest) (*ReloadZoneResponse, error)
	// NotifySecondaries sends NOTIFY to secondary servers
	NotifySecondaries(context.Context, *NotifyRequest) (*NotifyResponse, error)
	// TransferZone initiates a zone transfer (for secondary zones)
	TransferZone(context.Context, *TransferZoneRequest) (*TransferZoneResponse, error)
	// UpdateRecords adds/updates/deletes records (dynamic DNS)
	UpdateRecords(context.Context, *UpdateRecordsRequest) (*UpdateRecordsResponse, error)
	// GetRecords retrieves records from a zone
	GetRecords(context.Context, *GetRecordsRequest) (*GetRecordsResponse, error)
	// WatchZone streams zone change events
	WatchZone(*WatchZoneRequest, grpc.ServerStreamingServer[ZoneEvent]) error
	mustEmbedUnimplementedZoneServiceServer()
}

// UnimplementedZoneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZoneServiceServer struct{}

func (UnimplementedZoneServiceServer) ListZones(context.Context, *ListZonesRequest) (*ListZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListZones not implemented")
}
func (UnimplementedZoneServiceServer) GetZone(context.Context, *GetZoneRequest) (*GetZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetZone not implemented")
}
func (UnimplementedZoneServiceServer) ReloadZone(context.Context, *ReloadZoneRequest) (*ReloadZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadZone not implemented")
}
func (UnimplementedZoneServiceServer) NotifySecondaries(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifySecondaries not implemented")
}
func (UnimplementedZoneServiceServer) TransferZone(context.Context, *TransferZoneRequest) (*TransferZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferZone not implemented")
}
func (UnimplementedZoneServiceServer) UpdateRecords(context.Context, *UpdateRecordsRequest) (*UpdateRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRecords not implemented")
}
func (UnimplementedZoneServiceServer) GetRecords(context.Context, *GetRecordsRequest) (*GetRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecords not implemented")
}
func (UnimplementedZoneServiceServer) WatchZone(*WatchZoneRequest, grpc.ServerStreamingServer[ZoneEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchZone not implemented")
}
func (UnimplementedZoneServiceServer) mustEmbedUnimplementedZoneServiceServer() {}
func (UnimplementedZoneServiceServer) testEmbeddedByValue()                     {}

// UnsafeZoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZoneServiceServer will
// result in compilation errors.
type UnsafeZoneServiceServer interface {
	mustEmbedUnimplementedZoneServiceServer()
}

func RegisterZoneServiceServer(s grpc.ServiceRegistrar, srv ZoneServiceServer) {
	// If the following call panics, it indicates UnimplementedZoneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZoneService_ServiceDesc, srv)
}

func _ZoneService_ListZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ListZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_ListZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ListZones(ctx, req.(*ListZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_GetZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).GetZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_GetZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).GetZone(ctx, req.(*GetZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_ReloadZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).ReloadZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_ReloadZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).ReloadZone(ctx, req.(*ReloadZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_NotifySecondaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).NotifySecondaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_NotifySecondaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).NotifySecondaries(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_TransferZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).TransferZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_TransferZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).TransferZone(ctx, req.(*TransferZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_UpdateRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).UpdateRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_UpdateRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).UpdateRecords(ctx, req.(*UpdateRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_GetRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).GetRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZoneService_GetRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).GetRecords(ctx, req.(*GetRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZoneService_WatchZone_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchZoneRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZoneServiceServer).WatchZone(m, &grpc.GenericServerStream[WatchZoneRequest, ZoneEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZoneService_WatchZoneServer = grpc.ServerStreamingServer[ZoneEvent]

// ZoneService_ServiceDesc is the grpc.ServiceDesc for ZoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsscience.v1.ZoneService",
	HandlerType: (*ZoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListZones",
			Handler:    _ZoneService_ListZones_Handler,
		},
		{
			MethodName: "GetZone",
			Handler:    _ZoneService_GetZone_Handler,
		},
		{
			MethodName: "ReloadZone",
			Handler:    _ZoneService_ReloadZone_Handler,
		},
		{
			MethodName: "NotifySecondaries",
			Handler:    _ZoneService_NotifySecondaries_Handler,
		},
		{
			MethodName: "TransferZone",
			Handler:    _ZoneService_TransferZone_Handler,
		},
		{
			MethodName: "UpdateRecords",
			Handler:    _ZoneService_UpdateRecords_Handler,
		},
		{
			MethodName: "GetRecords",
			Handler:    _ZoneService_GetRecords_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchZone",
			Handler:       _ZoneService_WatchZone_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "zones.proto",
}
